### ISSUE TITLE
Prefix support

### ISSUE THREAD

**Issue by xkrt** [DataDog/datadogpy#113]
Please, add prefix support like Java and C#:
https://github.com/DataDog/dogstatsd-csharp-client/blob/master/src/StatsdClient/StatsdConfig.cs#L8
https://github.com/indeedeng/java-dogstatsd-client/blob/master/src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java#L120

**Comment by yannmh** [comment]
Adding it to our 0.11.0 milestone. 

Thanks @xkrt !
