### ISSUE TITLE
`dog` commandline tool does not auto-detect hostname

### ISSUE THREAD

**Issue by miketheman** [DataDog/datadogpy#115]
https://github.com/DataDog/datadogpy/blob/ac0857cc0402752d041dc6b7d6bf45b9ddd1b696/datadog/dogshell/common.py#L97-L98
https://github.com/DataDog/datadogpy/blob/e387239ab7c1aa84cc69cfe4bd18b63cead68ad0/datadog/dogshell/metric.py#L31-L34

This then requires each use of the `dog` command to specify the hostname, or the `--localhostname` argument, but there is no auto-detection in place for default.

My Principle of Least Surprise tells me that _something_ should be detected by default, and the user should be allowed to override it with command line flags, config file values, environment variables, etc.

**Comment by yannmh** [comment]
Thanks for the detailed report @miketheman. Assigning the ticket to our 0.11.0 milestone.

**Comment by drstevens** [comment]
It would be nice if `event post` command got this behavior as well

**Comment by yannmh** [comment]
Thanks for your feedback: I addressed the issue in #122 which I expect to be out next week with the `0.11.0` release.
