### ISSUE TITLE
Add support for Timers and Gauge deltas

### ISSUE THREAD

**Issue by yannmh** [DataDog/datadogpy#12]
<a href="https://github.com/alq666"><img src="https://avatars.githubusercontent.com/u/19755?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alq666](https://github.com/alq666)**
_Sunday Sep 22, 2013 at 15:26 GMT_
_Originally opened as https://github.com/DataDog/dogstatsd-python/issues/10_

---

**Comment by yannmh** [comment]
<a href="https://github.com/remh"><img src="https://avatars.githubusercontent.com/u/1311477?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [remh](https://github.com/remh)**
_Tuesday Nov 04, 2014 at 16:32 GMT_

----

Timers should be easy and probably done.

**Comment by jirikuncar** [comment]
Can anyone from @DataDog/agent-core confirm if it is implemented?

**Comment by arbll** [comment]
Gauge deltas are  not supported with dogstatsd see https://github.com/DataDog/dd-agent/pull/2104
Timers seems to be supported:
https://github.com/DataDog/datadogpy/blob/89f52f632cb97fe19d7e92e0266955fe33569afc/datadog/threadstats/base.py#L231

**Comment by jirikuncar** [comment]
@arbll thank you for the reference. Based on the information, I am closing this issue as it doesn't look like it will ever be fixed.
