### ISSUE TITLE
DD API does not support `related_event_id` when creating events

### ISSUE THREAD

**Issue by drstevens** [DataDog/datadogpy#121]
I'm not sure if this is an issue with the datadog API itself or simply unsupported behavior exposed by `dogshell` here https://github.com/DataDog/datadogpy/blob/master/datadog/dogshell/event.py#L81-L82

The datadog API does not currently support a `related_event_id` attribute when creating events. It is not documented http://docs.datadoghq.com/api/#events.

```
(python.2.7) $ dog --config /etc/dogrc event post --type=dave "dave.test.start" "This is a test event"
dave.test.start This is a test event  ()
2016-03-08 22:25:17 | https://app.datadoghq.com/event/event?id=442259632191669779
(python.2.7) $ dog --config /etc/dogrc event post --type=dave --related_event_id="442259632191669779" "dave.test.end" "This is a related test event"
ERROR: Invalid JSON structure
```

I have also tried posting the following json with curl with same result.

```
'{
      "title": "dave.related",
      "text": "dave related event",
      "priority": "normal",
      "alert_type": "info",
      "related_event_id": "442259632191669779"
  }'
```

I am able to successfully curl the following

```
'{
      "title": "dave.related",
      "text": "dave related event",
      "priority": "normal",
      "alert_type": "info"
  }'
```

**Comment by yannmh** [comment]
Thanks for the detailed report @drstevens. 

There is definitely something inconsistent here. We are investigating the issue, and will keep you informed as we found more about it.

**Comment by ajcrowe** [comment]
I'm experiencing this as well, is this likely something that will be resolved @yannmh?

**Comment by cswatt** [comment]
Send the value of `related_event_id` as an integer ID, i.e. without quotes. A pull request has been opened to better document this behavior. Thanks!

**Comment by drstevens** [comment]
@cswatt which PR is it? I'm not able to find it.

Are you suggesting that it should work if I remove the quotes when calling dogshell? e.g.

```
dog --config /etc/dogrc event post --type=dave --related_event_id=442259632191669779 "dave.test.end" "This is a related test event"
```
Instead of

```
dog --config /etc/dogrc event post --type=dave --related_event_id="442259632191669779" "dave.test.end" "This is a related test event"
```

**Comment by gzussa** [comment]
I think this is the PR https://github.com/DataDog/documentation/pull/4689
