### ISSUE TITLE
Library loads loggers that do not exist

### ISSUE THREAD

**Issue by miketheman** [DataDog/datadogpy#130]
Given a file `test.py`
Containing an example from the docs site:
```python
from datadog import initialize, api

options = {
    'api_key': '<REDACTED>',
    'app_key': '<REDACTED>'
}

initialize(**options)

api.Monitor.get(2081)
```

When executing `python test.py`
Then this message is observed:
```
No handlers could be found for logger "dd.datadogpy"
```

This is not an error, and if we set up Python loggers that match this, it will likely work, but for a simple example, I do not expect to need to set up a logger to prevent this output.

**Comment by miketheman** [comment]
I am unable to reproduce this today with current master, not can I point out when this was resolved.
Closing as a mystery.

**Comment by tkensiski** [comment]
I am hitting this issue as well right now.

```
from datadog import initialize, api

options = {
    'api_key': '==REDACTED==',
    'app_key': '==REDACTED=='
}

initialize(**options)

for monitor in api.Monitor.get_all():
    print monitor```

**Comment by tkensiski** [comment]
So did some debugging a bit later last night and turns out that it was due to my tethered connection while commuting.

I think we might need to increase the timeouts a bit?

**Comment by tkensiski** [comment]
I am getting this issue off and on, it looks like timeout issues against http requests.

I added a retry block around my monitor fetcher and now that it keeps retrying until it it succeeds it works. but it takes a while sometimes.

**Comment by yannmh** [comment]
Thanks for the feedback @tkensiski. I opened the issue back, and moved it to the upcoming milestone. 
It will get the attention it needs for the next release 🔨

**Comment by avaughan89** [comment]
This came up again on for ticket# 64510

Appears to be a syntax issue oddly.  Copying straight from customer example provided same error but copying example straight from: http://docs.datadoghq.com/api/#timeboards  Did not produce same error.  Could be unrelated.

**Comment by BeneHa** [comment]
I have this issue as well when trying to create a simple monitor. Is there any workaround I can use right now? Retrying also does not work in my case.

**Comment by tkensiski** [comment]
So I was able to "resolve" this issue by setting a higher timeout.

Heres how you do it:

```
options = {
    'api_key': api_key,
    'app_key': app_key,
    'timeout': 10
}

initialize(**options)
```

This will set the timeout to 10 seconds instead of the default 3.

The real fix would be if Datadog improved their API so we all can filter on the get all endpoint (using tags or names) so we are not returning 100's of monitors which is whats causing this issue for my team.

**Comment by BeneHa** [comment]
I wrote another script creating monitors, just a bit more complex, which works fine now for some reason. Did not run into this error once, I am using the exact same line for the API call.

**Comment by yannmh** [comment]
> Edit: worked the whole morning, now not any more. When using the timeout option I get an error saying I am using an old version of requests, which is incorrect.

Can you open a new issue with the trace of the error as well as a snapshot of your `pip freeze` please? I believe this could be a different issue. Thank you

**Comment by tkensiski** [comment]
@yannmh Yes, tags only work for the tags auto added based on the filters added to a query and not the tags that I add via the API. As for group states most of our monitors are in the same state so this doesn't help slim the result set down at all either.

I am trying to manage monitors programmatically which may include creating, deleting, updating and so on.

**Comment by yannmh** [comment]
@tkensiski We are updating the monitor API endpoint to support monitor & scope tag filtering.
It's currently being reviewed and tested on staging. 

This should go out pretty soon now 🚢

**Comment by yannmh** [comment]
Fixed with https://github.com/DataDog/datadogpy/pull/161.

Please see https://github.com/DataDog/datadogpy/blob/master/CHANGELOG.md#0140--unreleased for more information.
