### ISSUE TITLE
Threadstatsd set metric

### ISSUE THREAD

**Issue by johnistan** [DataDog/datadogpy#131]
There appears to be a disconnect between dogstatd and threadstatsd.

the `set` method is not supported. What is the equivalent in the thread version?

https://github.com/DataDog/datadogpy/blob/master/datadog/dogstatsd/base.py#L227

**Comment by yannmh** [comment]
Hey @jofusa,

You are right, the `set` method is currently missing from the `ThreadStats` module. 
Unfortunately, I can't think about any equivalent that would not require to maintain a local Python's `set()`, whose size would be submitted a `gauge` and reset.

In the meantime, I am adding this issue to our `0.12.0` milestone, so it get addressed in the next release.
