### ISSUE TITLE
Unicode Characters in Tags Cause Problems

### ISSUE THREAD

**Issue by cshoe** [DataDog/datadogpy#132]
Seen in datadogpy 0.9.0 and 0.11.0 using Python 2.7.6 and 2.7.11.

It doesn't seem possible to use unicode characters in tags. Running the following causes an ``UnicodeDecodeError`` to be raised from the [use of ``str`` here](https://github.com/DataDog/datadogpy/blob/master/datadog/dogstatsd/base.py#L267):

```python
# -*- coding: utf-8 -*-

from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

from datadog import statsd

statsd.increment('tagged_counter', 1, tags=['person:Jóhn', 'foo:bar'])
```

If the tags are encoded before they are sent to datadogpy, the error is raised in 0.11.0 [a couple lines before when the payload is being constructed](https://github.com/DataDog/datadogpy/blob/master/datadog/dogstatsd/base.py#L265).

```python
# -*- coding: utf-8 -*-

from __future__ import (absolute_import, division, print_function,
                        unicode_literals)

from datadog import statsd

statsd.increment('tagged_counter', 1, tags=['person:Jóhn'.encode('utf-8'), 'foo:bar'])
```

**Comment by yannmh** [comment]
Thanks for reporting the issue @cshoe.

I am adding it to our `0.12.0` milestone, so it gets fixed in the next release.
