### ISSUE TITLE
_report() should not mutate tags param

### ISSUE THREAD

**Issue by albertc1** [DataDog/datadogpy#133]
At https://github.com/DataDog/datadogpy/blob/master/datadog/dogstatsd/base.py#L252 in the _report method that gets called for each metric reported, we append self.constant_tags to whatever the user has passed in as the tags param.  This creates a problem is the user is passing in a class variable or global variable as the tags param, since it would grow larger and larger with each metric reported.

For example:

```
statsd = DogStatsd(constant_tags=['const_tag'])

class MemoryLeaker(object):
    tags = ['class_tag']

    @classmethod
    def report_metric(cls):
        statsd.increment('my_metric', tags=tags)
```

Each time MemoryLeaker.report_metric() is called, MemoryLeaker.tags gets another instance of 'const_tag' appended to it.  Ideally, dogstatsd would make a local copy of that array instead of modifying the original.

**Comment by yannmh** [comment]
This is definitely an issue. Thanks for reporting it as well as for the detailed feedback @albertc1.

I am adding it to our `0.12.0` milestone: it will fixed in the upcoming release.

**Comment by yannmh** [comment]
This was fixed with https://github.com/DataDog/datadogpy/commit/d68749cd09f9261b43cc1e9a4677a9468e8421b4.

Thanks again.
