### ISSUE TITLE
api.Event.create returns false OK when bad tags are passed.

### ISSUE THREAD

**Issue by xtaje** [DataDog/datadogpy#138]
Using the python api, sending an event with tags=0xdeadbeef will return with status = 'ok', and a formatted url.

The event never shows up in the datadog web ui, and the link provided in the response gives a 404 error.

**Comment by xtaje** [comment]
This will work if you provide a string, or an array of strings.

**Comment by yannmh** [comment]
Thanks for reporting the issue @xtaje.

I realize that's probably related to the API itself, not the Python client. I'll look more into it and reach out with more information.

**Comment by yannmh** [comment]
@xtaje, this is a behavior from the `POST /api/v1/events` endpoint, not the Python client. 
We could add an extra step in the client to assess the format of the tags before posting them to Datadog, but I don't think this is ideal: in my opinion, the client should stay as agnostic as possible to the backend.  

On the API side, we are aware of this limitation. Unfortunately we don't have any short-term solution to fix it now: the endpoint performs a minimal validation on the payloads which are processed later on in the pipeline.

I am going to close this issue. I won't miss to keep you informed if something changes.

Thanks again
