### ISSUE TITLE
DNS update to statsd host not respected by client

### ISSUE THREAD

**Issue by aelse** [DataDog/datadogpy#141]
If the IP address of the statsd host changes the client does not pick this up. The client maintains an open socket to the statsd host after first use and this is only recreated when a detectable error occurs.

https://github.com/DataDog/datadogpy/blob/master/datadog/dogstatsd/base.py#L102-L109

**Comment by yannmh** [comment]
> The client maintains an open socket to the statsd host after first use and this is only recreated when a detectable error occurs.

That sounds like the desired behavior. Resolving the host name at every `statsd` call would add some (must of the time unnecessary) overhead. Is there any alternative you would think of ?

Thanks

**Comment by aelse** [comment]
I know it's a bit tricky, and I don't have an elegant solution.

1. In the case of host resolved by DNS the client could honour the TTL and on expiry rebuild the socket if the record resolves differently.
2. Or, a thread/greenlet could regularly perform a lookup to do the same (which should work also in the non-DNS case, but might be troublesome with DNS servers returning round-robin results)
3. Or, expose a way to deal with this

I experimented briefly with something like the last option, directly updating the socket object in the DogStatsd client instance, but in the end switched to the ThreadStats client to solve my immediate concern.

I've since had a look at a few other statsd clients and several of them exhibit similar behaviour, so attacking it from this direction is probably a lost cause. It needs to be dealt with at the infrastructure level.

Thanks anyway.

**Comment by yannmh** [comment]
Thanks for your additional input on this.
