### ISSUE TITLE
dogrc file shouldn't be required if api/app key env vars are set

### ISSUE THREAD

**Issue by clofresh** [DataDog/datadogpy#144]
```
$ DATADOG_API_KEY=foo DATADOG_APP_KEY=bar dog timeboard show_all
~/.dogrc does not exist. Would you like to create it? [Y/n] 
```

Even tho though env vars are used later on in the init https://github.com/DataDog/datadogpy/blob/master/datadog/__init__.py#L63-L64

This makes it difficult to automate things that only have access to env vars and not the file system.

**Comment by yannmh** [comment]
We'll fix that in the next release. Thanks @clofresh.

**Comment by andyshinn** [comment]
This has been bumped for a while now. Is it something more difficult than worth? My use case is to be able to use the utility for metrics and event posting from CI solutions where I just pass the environment variables or the param on CLI.
