### ISSUE TITLE
statsd_use_default_route triggers failure on OSX

### ISSUE THREAD

**Issue by miketheman** [DataDog/datadogpy#156]
We often develop on OSX, and use a common settings file to initialize the library.

With the setting of use_default_route on OSX, we trigger this easily-reproducible failure:

```python
>>> from datadog import initialize, statsd
>>> datadog_options = { 'statsd_use_default_route': True }
>>> initialize(**datadog_options)
>>> statsd.increment('test')
No handlers could be found for logger "dogstatsd"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/miketheman/.../python-2.7.12/lib/python2.7/site-packages/datadog/dogstatsd/base.py", line 153, in increment
    self._report(metric, 'c', value, tags, sample_rate)
  File "/Users/miketheman/.../python-2.7.12/lib/python2.7/site-packages/datadog/dogstatsd/base.py", line 298, in _report
    self._send(encoded)
  File "/Users/miketheman/.../python-2.7.12/lib/python2.7/site-packages/datadog/dogstatsd/base.py", line 303, in _send_to_server
    (self.socket or self.get_socket()).send(packet.encode(self.encoding))
  File "/Users/miketheman/.../python-2.7.12/lib/python2.7/site-packages/datadog/dogstatsd/base.py", line 110, in get_socket
    sock.connect((self.host, self.port))
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

[_get_default_route](https://github.com/DataDog/datadogpy/blob/0c87da34bdcd0a6b0efc79e68026f752d5d425c0/datadog/dogstatsd/base.py#L86-L96) is failing to find the `/proc/net/route` file - it doesn't exist on OSX, but the `log.error` is never seen, `None` is returned, and used in [`get_socket`](https://github.com/DataDog/datadogpy/blob/0c87da34bdcd0a6b0efc79e68026f752d5d425c0/datadog/dogstatsd/base.py#L110), which is an invalid input.

[Current unit test](https://github.com/DataDog/datadogpy/blob/0c87da34bdcd0a6b0efc79e68026f752d5d425c0/tests/unit/dogstatsd/test_statsd.py#L68-L74) confirms that the option is set post-initialize, but not whether the resulting client works. I did not see a relevant integration test for this.

I don't know if the right answer is to add a condition from `sys.platform` and use the equivalent of something like one of these for OSX:
- `netstat -rn | grep 'default' | awk '{print $2}'`
- `route -n get default | grep 'gateway' | awk '{print $2}'`

**Comment by yannmh** [comment]
Fixed with https://github.com/DataDog/datadogpy/pull/166. 

This will go out with the `0.15.0`. Thanks @miketheman !

**Comment by miketheman** [comment]
@yannmh Thanks - I don't see the fix on any branch, is it hiding somewhere?

**Comment by yannmh** [comment]
Pressed the wrong button ('M̶e̶r̶g̶e̶'→ Close') :facepalm:

It's now on `master` 🙇

**Comment by miketheman** [comment]
@yannmh Any chance of an 0.15.0 release anytime soon?

**Comment by yannmh** [comment]
Hey @miketheman,

We are planning a release next week, before Thursday 🚀
