### ISSUE TITLE
Support a `roll_up_period` of 0 or None

### ISSUE THREAD

**Issue by yannmh** [DataDog/datadogpy#17]
<a href="https://github.com/conorbranagan"><img src="https://avatars.githubusercontent.com/u/472446?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [conorbranagan](https://github.com/conorbranagan)**
_Monday Aug 26, 2013 at 23:02 GMT_
_Originally opened as https://github.com/DataDog/dogapi/issues/61_

---

Right now if you submit a metric than immediately flush, you won't get the metric out because it won't be after the `roll_up_period` has passed.

If we could accept a None value for the roll-up period, then we could ignore it on flushes.

**Comment by Daenyth** [comment]
Looks related to #217

**Comment by jirikuncar** [comment]
Fixed by #221
