### ISSUE TITLE
simplejson error -- related to 3.9.0 release? 

### ISSUE THREAD

**Issue by kwwalter** [DataDog/datadogpy#173]
Hey all, a user reached out today and said he started running into this issue once simplejson 3.9.0 was released today: 

`Processing dependencies for datadog Searching for simplejson>=2.0.9 Reading https://pypi.python.org/simple/simplejson/ Best match: simplejson 3.9.0.macosx-10.10-x86-64 Downloading https://pypi.python.org/packages/9a/b8/63af70ed65188305041b62e2d2ec4f5aac076771b859a4595f69cf815df4/simplejson-3.9.0.macosx-10.10-x86_64.tar.gz#md5=4357c0b875bda4afbd36d940d4e4e4aa Processing simplejson-3.9.0.macosx-10.10-x86_64.tar.gz STDERR: error: Couldn't find a setup script in /tmp/easy_install-F6YozO/simplejson-3.9.0.macosx-10.10-x86_64.tar.gz ---- End output of easy_install datadog ---- Ran easy_install datadog returned 1`

He's running ubuntu on AWS. Could you please have a look? Thanks!

**Comment by yannmh** [comment]
Works well on my side.

Also, can you advise the user to try with `pip` instead of `easy_install` please?

**Comment by kwwalter** [comment]
will do, thanks @yannmh
