### ISSUE TITLE
ThreadStats methods use `metric_name` instead of `metric`

### ISSUE THREAD

**Issue by dblackdblack** [DataDog/datadogpy#175]
I'm trying to wrap datadog in a generic class that uses a ThreadStats object on heroku (where dogstatsd isn't running) but a regular DogStatsd object on EC2 (where dogstatsd is running).  I'm stymied in this by the fact that the basic statsd methods (`increment()`, `gauge()`, and `timing()`) have slightly different calling signatures for ThreadStats and DogStatsd.  In particular DogStatsd uses `metric` whereas ThreadStats uses `metric_name`.

Please write a shim or function decorator or something that lets downstream consumers of the classes call these methods using either `metric` or `metric_name` in the calling signature.

**Comment by yannmh** [comment]
Thanks for reporting @dblackdblack.

This is indeed an issue and should be fixed!

**Comment by jirikuncar** [comment]
@dblackdblack are you still interested in fixing it? We try to be 100% backward compatible, hence we would need to add new keyword argument at the end as explained in https://github.com/DataDog/datadogpy/pull/184#issuecomment-576842824. What do you think about it?

**Comment by zippolyte** [comment]
We cannot change the parameter since we need to stay backward compatible.
