### ISSUE TITLE
DeprecationWarning for config.py

### ISSUE THREAD

**Issue by donato** [DataDog/datadogpy#178]
Hi all, we are seeing our logfiles get polluted with datadog warnings which look like this:

```
/app/python/lib/python3.5/site-packages/datadog/util/config.py:116: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
  config.readfp(skip_leading_wsp(open(config_path)))
```

Using Python 3.5 with version of datadog==0.14.0

**Comment by yannmh** [comment]
Thanks @donato,

We are working on it for the next release 🚀

**Comment by zippolyte** [comment]
Fixed in https://github.com/DataDog/datadogpy/pull/451, closing
