### ISSUE TITLE
Mock/disable statsd during tests

### ISSUE THREAD

**Issue by z1IB6p** [DataDog/datadogpy#183]
I'm using `datadog.statsd` in a few place in my codebase, when I run my tests I see:

`INFO datadog.dogstatsd:259 Error submitting packet, will try refreshing the socket`

Is there a way I can mock/disable `statsd`during my tests? (Preferably mock it or switch it off rather than changing the loggers).

**Comment by yannmh** [comment]
Hey @z1IB6p,

This is how we do it in our own tests: https://github.com/DataDog/datadogpy/blob/master/tests/unit/dogstatsd/test_statsd.py#L68

You could also simply write something like
```python
from datadog import statsd
from mock import Mock

statsd.socket = Mock()
```

**Comment by yannmh** [comment]
I haven't heard back from you @z1IB6p.

I am closing this issue, but please feel free to re-open if you are still experiencing troubles.
