### ISSUE TITLE
Enable dogwarp to read /etc/dd-agent/datadog.conf?

### ISSUE THREAD

**Issue by kbaltrinic** [DataDog/datadogpy#188]
Similar to https://github.com/DataDog/datadogpy/issues/107, the `dogwrap` cli should support a flag telling it to pull the API key and (optionally?) tags from `/etc/dd-agent/datadog.conf`

**Comment by colinmollenhour** [comment]
I just came here to open this exact same issue.. As I start using dogwrap it seems senseless, less secure and harder to automate configuration deployments when the API key must be specified on the CLI yet it already exists in a location which in nearly all cases should be safe to assume. 👍

**Comment by moolitayer** [comment]
@dabcoder in agent 6 are tags taken into account from datadog.yaml ?

**Comment by dabcoder** [comment]
@moolitayer No they aren't. We have not implemented any feature that allows to fetch tags/keys from the Datadog agent configuration file.

**Comment by zippolyte** [comment]
Hey folks,

We don't plan on supporting reading from the agent configurations.
However, it's true that having to specify the API key in the command line directly is not great practice, so we decided to allow dogwrap to read the API key from the usual `DD_API_KEY` environment variable when it is not specified in the command line.
This has been done in #543.

Closing this issue now

**Comment by colinmollenhour** [comment]
Thanks, the env variable will definitely be an improvement!
