### ISSUE TITLE
dog_stats_api doesn't encode pipe char

### ISSUE THREAD

**Issue by yannmh** [DataDog/datadogpy#19]
<a href="https://github.com/clofresh"><img src="https://avatars.githubusercontent.com/u/15370?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [clofresh](https://github.com/clofresh)**
_Friday Feb 21, 2014 at 23:23 GMT_
_Originally opened as https://github.com/DataDog/dogapi/issues/81_

---

`|` is used by the statsd protocol to delimit the fields, so if you use it in a tag, you'll lose whatever's after the pipe

**Comment by jirikuncar** [comment]
@DataDog/agent-core should the `|` in tag be escaped or we should not allow tags with `|`?

Is there any documentation which specifies valid tags? I have only found https://docs.datadoghq.com/developers/metrics/dogstatsd_metrics_submission/?tab=python#metric-tagging.

**Comment by arbll** [comment]
@jirikuncar https://docs.datadoghq.com/tagging/#defining-tags defines valid characters for tags. AFAIK statsd/dogstatsd do not specify how to escape characters that conflict with the protocol or are invalid. It probably make sense to either strip them or replace them by a valid character like `_`.

In any case let's make sure we align with other clients if they have logic to escape tags / metric names.

**Comment by jirikuncar** [comment]
@arbll thank you for the link. It doesn't say how the tags should be encoded in case of `dogstatd`. We can add a validation, but `|` seems like a valid character.

**Comment by arbll** [comment]
@jirikuncar `|` is invalid for all datadog tags, so it's also invalid for dogstatsd. 
Again, I don't think dogstatsd/statsd escaping is defined anywhere. See https://github.com/statsd/statsd/issues/585 for example

**Comment by jirikuncar** [comment]
@arbll so basically a tag has to match `^[A-Za-z][A-Za-z0-9_\-:,/]{0,199}$` after `re.sub('[^A-Za-z0-9_\-:,/]', '_', tag)`.

---
Playground: https://regex101.com/r/yJ8qva/1/tests

**Comment by zippolyte** [comment]
closed in https://github.com/DataDog/datadogpy/pull/517
