### ISSUE TITLE
Creating an event with parameter 'source_type_name' doesn't work

### ISSUE THREAD

**Issue by neurolabs** [DataDog/datadogpy#191]
I'm trying to create an event like this:

```
api.Event.create(title=sys.argv[1], text=sys.argv[2], tags=sys.argv[4:], aggregation_key=sys.argv[3], alert_type="success", source_type_name="jenkins")
```

It does not show up in the event list. If I leave out the parameter 'source_type_name', it works.

When calling with the parameter, I get the following output opposed to without:

```
hostname: Unknown host
```

**Comment by nmuesch** [comment]
Hey, @neurolabs Sorry for not responding sooner here. Are you still encountering this issue? I'm not able to reproduce with the latest version of datadogpy. 

```
api.Event.create(title='Sample Title', text='Sample text', tags=['foo:bar'], alert_type="success", source_type_name="jenkins")
```

Seems to properly create the event as expected.

**Comment by neurolabs** [comment]
Sorry @nmuesch I am not using datadog ATM. I am closing this, since you verified that it works from your perspective.
