### ISSUE TITLE
Docstrings say most functions return JSON, but really they return dicts

### ISSUE THREAD

**Issue by kmshultz** [DataDog/datadogpy#193]
One user brought this up.

e.g. in Metric.query's docstring:

> :return: JSON response from HTTP request

Yet:

```
>>> metric_query = api.Metric.query(start=int(time.time()) - 3600, end=int(time.time()), query='avg:system.cpu.idle{*}')
>>> type(metric_query)
<type 'dict'>
```

I'm not sure if we want to fix the docstring, or really fix all functions to return JSON strings (i.e. not `json.loads` the response in `APIClient.submit()`) instead of dicts.

I see there's a `response_formatter` keyword arg, but no code that calls `APIClient.submit()` seems to use it.

**Comment by yannmh** [comment]
You are right @kmshultz, it's actually an abuse of language. 

I suggest here that we fix the docstrings rather than returning a JSON formatted string.

**Comment by kmshultz** [comment]
Just opened #197, please review when you have a moment. Thanks!
