### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by remh** [DataDog/datadogpy#2]
It will be easier for contributors to contribute and for people who want to to fork it to fork it.

I recommend the Simplified BSD License
https://raw.githubusercontent.com/DataDog/dogstatsd-python/master/LICENSE

**Comment by miketheman** [comment]
Might want to touch base with @alq666 on whether we should be using Apache, MIT, or BSD.

**Comment by alq666** [comment]
Apache, MIT or BSD are fine. BSD is a good way to go.

**Comment by yannmh** [comment]
Thank you. Just added a 3-clause BSD license.
