### ISSUE TITLE
Create documentation on how to add tests.

### ISSUE THREAD

**Issue by ronindesign** [DataDog/datadogpy#205]
Some documentation should be added on how to actually add tests.

I'm rather new to python, but from what I can tell, tests are being managed / chained:
pytest / travis-ci -> tox -> nose -> unittest

However, it seems like tests in `tests.integration`, `tests.util` not being ran...

**Comment by ronindesign** [comment]
Turns out there was misconfiguration (or intentionally not configured) tests. Adding `__init__py` to directories now runs tests.

Still need documentation / examples on how to add tests (and maybe available packages for helping with testing, e.g. `ConfigParser`)

**Comment by yannmh** [comment]
> However, it seems like tests in tests.integration, tests.util not being ran...
> Turns out there was misconfiguration (or intentionally not configured) tests. Adding __init__py to directories now runs tests.

It's indeed intentionally not configured. I figured out those extra tests are more testing the API endpoints than the actual Python client. It can be flaky and slow, so I left them out of the CI, but available if one wants to run end-to-end testing. I agree it's disconcerting and I will add a note about that.

> Still need documentation / examples on how to add tests (and maybe available packages for helping with testing, e.g. ConfigParser)

👍

**Comment by ronindesign** [comment]
Yep, that's no problem at all, I feel it was well implied by the different sub-directory (e.g. 'integration' vs 'unit').

Any specific recommendation for how to add (unit) tests that are related to the datadogpy / client side?
For example, I initially just wanted to simply add some unit tests around handling unicode input/output for the `dogshell.wrap` (which becomes executable `dogwrap`).

However, as can be seen from the integration tests, an intermediate "subprocess" handler is required to call the binary in the first place which adds to the test complexity. Then, to completely or fully test that unicode is working, the content would still need to be submitted to the DataDog API service, which as you said is more in the realm of integration.

So would it make sense to just have client side testing that the API call is made without, say, a python exception, and only assert on things the client has immediately available (e.g. `stdout`, `stderr`)? Or maybe there is a way to mock the API call, so that again only the client side is tested?

Not quite sure where a good balance between test coverage and localizing to the client could be made there, so any suggestions would be appreciated. Mostly just want to get some unicode support testing in place.

**Comment by jirikuncar** [comment]
I don't think we have any specific rules apart from common sense. All contributions are welcome and reviewers will help you to structure your code and tests when you submit a PR. We are not documenting "best practices" as they evolve over time and we are open to new ideas.

Here are good starting points for some of the questions you had:
- PyTest framework: https://docs.pytest.org/en/latest/
- Unit testing: https://en.wikipedia.org/wiki/Unit_testing
- Integration testing: https://en.wikipedia.org/wiki/Integration_testing
