### ISSUE TITLE
Multiple dogshell.dog monitor unmute_all calls are successful.

### ISSUE THREAD

**Issue by ronindesign** [DataDog/datadogpy#208]
DataDog API does not correctly throw error on requesting `api/monitor/unmute_all` when 'mute_all' not currently set.

Signature: `POST /api/v1/monitor/unmute_all`
> UNMUTE ALL MONITORS
Disables muting all monitors. Throws an error if mute all was not enabled previously.

Ref: http://docs.datadoghq.com/api/#monitor-unmute-all

Example for testing:
```shell
curl -X POST "https://app.datadoghq.com/api/v1/monitor/unmute_all?api_key=APIKEY&application_key=APPKEY"
```

Currently, last assert in `datadog.dogshell.test_dogshell.test_monitors` fails for, correctly, for this. So, abnormally, this issue is actually not a bug in the package, it is with the service API itself.

This ticket should be closed when either the service is fixed to throw error correctly, or when documentation has been updated. In the event of the latter, we can update the test to reflect the new behavior.

**Comment by yannmh** [comment]
Thanks @ronindesign, I was able to reproduce the issue.

I am following internally to see whether we want to fix the endpoint behavior or the documentation.

**Comment by ronindesign** [comment]
The last message from support closed my ticket on the issue, stating:
> Currently they are working on several other issue that have taken a higher priority at the moment but we will surely get back to you on this via the repository.

So, if you hear otherwise, please feel free to adjust this issue here accordingly, or simply close it out if there is no movement. I'll leave it open now for you to decide, ether way it can be readdressed when there is movement on it.

Thanks for the response!

**Comment by ronindesign** [comment]
This was fixed / resolved at some point today. Now multiple requests result in correct exceptional behavior:
```shell
curl -X POST "https://app.datadoghq.com/api/v1/monitor/unmute_all?api_key=APIKEY&application_key=APPKEY" 
{"errors":["Monitoring is not currently globally muted"]}
```
