### ISSUE TITLE
dogshell - allow dogrc file placement outside home directory

### ISSUE THREAD

**Issue by yannmh** [DataDog/datadogpy#21]
<a href="https://github.com/celenechang"><img src="https://avatars.githubusercontent.com/u/6087353?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [celenechang](https://github.com/celenechang)**
_Tuesday May 13, 2014 at 18:24 GMT_
_Originally opened as https://github.com/DataDog/dogapi/issues/90_

---

this would be useful for multiple users to use the same dogrc file

**Comment by yannmh** [comment]
<a href="https://github.com/clofresh"><img src="https://avatars.githubusercontent.com/u/15370?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [clofresh](https://github.com/clofresh)**
_Tuesday May 13, 2014 at 18:36 GMT_

----

You can specify the location of the dogrc config file to with `dog --config`, is that you're looking for?

**Comment by yannmh** [comment]
<a href="https://github.com/conorbranagan"><img src="https://avatars.githubusercontent.com/u/472446?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [conorbranagan](https://github.com/conorbranagan)**
_Tuesday May 13, 2014 at 18:38 GMT_

----

This is more about having one of the default config lookups be `/etc/datadog/dogrc` so you don't always have to specify a config when using it across multiple users

**Comment by Julian** [comment]
I'm not sure if it's included in the original request, but respecting `XDG_CONFIG_HOME` might also be nice.

**Comment by jirikuncar** [comment]
It should be easy to implement in `DogshellConfig` while setting a default `--config` value to `None`.

```python
def dogrc_locations():
    """Yield possible locations of dogrc configuration file."""
    # TODO
```

**Comment by zippolyte** [comment]
Closing, as we can specify the config file with `--config`, and there is no demand to change the default location.
