### ISSUE TITLE
Django middleware, Django integration

### ISSUE THREAD

**Issue by bittner** [DataDog/datadogpy#211]
Would you be interested in integrating a Django middleware into this package? Something like [django-datadog](https://github.com/conorbranagan/django-datadog)?

This would be a rather small amount of code, and would make the integration with Python software very easy, e.g.

> Just install a single package -- via `pip install datadog` -- and add a single line to your Django application's settings, and you're all set -- for reporting of exceptions to DataDog.

See https://github.com/conorbranagan/django-datadog/issues/5 for a related discussion.

**Comment by gzussa** [comment]
Hi,
You can now use APM for this use case. Here is the library you should use https://github.com/DataDog/dd-trace-py. Here is the Django integration https://github.com/DataDog/dd-trace-py/tree/master/ddtrace/contrib/django and here is the documentation http://pypi.datadoghq.com/trace/docs/

Enjoy 😄
