### ISSUE TITLE
Event calls with incorrect alert_type fail silently

### ISSUE THREAD

**Issue by onlyanegg** [DataDog/datadogpy#215]
In the event api, post event calls with incorrect `alert_type` fail silently. I would expect some type checking to be done and an error to be returned. 

I'm using the Python API. Stepping into `create()` in events.py I can see params contains the following: 

```
{
  "date_happened": None,
  "alert_type": "ahhhh",
  "tags": None,
  "text": "testing  events",
  "title": "test",
  "priority": None,
  "host": None,
  "aggregation_key": None,
  "source_type_name": None
}
```

Here's the response: 

```
{
  "status": "ok",
  "event": {
    "date_happened": 1498946344,
    "handle": null,
    "title": "test",
    "url": "https://app.datadoghq.com/event/event?id=1138017950882477404",
    "text": "testing datadog events",
    "tags": null,
    "priority": null,
    "related_event_id": null,
    "id": 1138017950882477400
  }
}
```

But no event gets created in the UI. I understand that `alert_type` can be one of "error", "warning", "info", and "success", but I would expect there to be an error response for incorrect alert types.

**Comment by dabcoder** [comment]
Apologies for the very late response, but we aimed to fix this in #467 thanks for the feedback.
