### ISSUE TITLE
Issue when using a list for `hosts` parameters

### ISSUE THREAD

**Issue by pmourlanne** [DataDog/datadogpy#216]
The documentation says that the `hosts` argument for `Event.create` is a list of strings : https://github.com/DataDog/datadogpy/blob/master/datadog/api/events.py#L48

When using a list of strings as host:
```
datadog.api.Event.create(**{
   'title': 'plop',
   'text': 'alo',
   'host': ['firsthost, 'secondhost', ],
})
```

The datadog API answers:
```
{'errors': ['Invalid JSON structure']}
```

I think the documentation should be updated to say the `host` argument expects a string.

**Comment by yannmh** [comment]
Apologies for the late answer @pmourlanne. 

I fixed the documentation with #220.
