### ISSUE TITLE
ThreadStats doesn't flush remaining metrics

### ISSUE THREAD

**Issue by brettlangdon** [DataDog/datadogpy#217]
When doing the following, no metrics are reported.

```python
from datadog import initialize
from datadog import ThreadStats


initialize(api_key="api_key", app_key="app_key")

stats = ThreadStats()
stats.start()
stats.gauge("test.foo", 1)
stats.flush()
stats.stop()
```

It appears that when we flush `stats` it'll only flush metrics that belong to previous rollup intervals and will always ignore the current interval.

I can fix this issue by doing the following to trick it to think that more time has past.

```python
import time

stats.flush(time.time() + 10)
```

This seems to be an issue for short running environments like `lambda` functions.

**Comment by yannmh** [comment]
This would be fixed with https://github.com/DataDog/datadogpy/pull/221. Please let me know how that would work for you 🙇

**Comment by austinmills** [comment]
We're running into this right now for short-lived python code. It looks like there's a PR?

**Comment by sylvestre** [comment]
@LeoCavaille ^^ if you can help!

**Comment by irabinovitch** [comment]
@austinmills Apologies for the delay #221 is now merged.

**Comment by jmehnle** [comment]
@brettlangdon, can you still reproduce the faulty behavior or does the merge of #221 resolve this issue?

**Comment by gzussa** [comment]
Seems this is working now

**Comment by carlosrochap** [comment]
I'm still seeing this issue.  Doing stats.flush(time.time() + 10) seems to fix it

**Comment by dabcoder** [comment]
@carlosrochap Sorry for the delay. Is that definitely fixed with that option set to `False`? Let us know if we need to reopen this issue and look into it.

**Comment by carlosrochap** [comment]
@dabcoder nope, I decided to stop using this and decided to use the agent running on k8s
