### ISSUE TITLE
Add tags within the scope of the execution function

### ISSUE THREAD

**Issue by rue-mishakorablin** [DataDog/datadogpy#222]
I'm writing an API client that tracks call duration as well as response error counts. I would like to tag each different API call with `name:<api_call_name>`. What is a good way to do so?

My code looks something like this:
```
def make_request(endpoint):
    try:
        response = request.get(endpoint)
        results = response.json()
    except:
        # handle errors here
    finally:
        # Ideally I'd prefer to add these tags in the beginning of the method and don't pass them explicitly into every call, but this works as well.
        statsd.increment('calls', tags=['role:myapi'])
        statsd.histogram('duration', response.elapsed, tags=['role:myapi']

    return results

def call_endpoint_A(options):
    # At this point I'd like to make sure all subsequent calls until the end of this function will have
    # an extra tag `'name:endpoint_A'`.
    return make_request('/endpoint_a')
```

**Comment by yannmh** [comment]
@rue-mishakorablin,

You can achieve that by using the `statsd.timed` decorator. For example:

```python
from datadog import statsd

@statsd.timed()
def make_request():
      try:
        response = request.get(endpoint)
        results = response.json()
    except:
        # handle errors here
```


The snippet would result in `<python_module>.make_request.*` histogram metrics which includes a counter, and various durations (min, max, avg, 95p...).

An other alternative is to use Datadog tracing and the Python trace client https://github.com/DataDog/dd-trace-py

**Comment by gzussa** [comment]
Closing this since it has been answered
