### ISSUE TITLE
dogshell, when posting metrics does not check for NoneType responses. 

### ISSUE THREAD

**Issue by xtreme-jesse-malone** [DataDog/datadogpy#243]
https://github.com/DataDog/datadogpy/blob/master/datadog/dogshell/metric.py#L53-L58

I've encountered this error periodically while posting metrics. It seems like there's an assumption that the api response will never be 'None' but seems like occasionally it is. Not sure if there's a good way to handle those cases, but at least a clear error message would improve things.

```
Traceback (most recent call last):
  File "/usr/local/bin/dog", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/datadog/dogshell/__init__.py", line 69, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/datadog/dogshell/metric.py", line 58, in _post
    res = defaultdict(list, res)
TypeError: 'NoneType' object is not iterable
```

**Comment by dabcoder** [comment]
Apologies for the long delay in updating this thread. Are you still experiencing this issue? I was not able to reproduce this, so it would be good to get more details on the actual `dog metric` command you are using.
