### ISSUE TITLE
Feature request: Enable logging (levels) when using the dog cli

### ISSUE THREAD

**Issue by sukhil-suresh** [DataDog/datadogpy#244]
Would it be possible to enable verbose logging for the `dog cli` through say an environment variable (DOG_LOG_LEVEL) or a command flag (--verbose)? It would be very handy for debugging. Eg. being able to see the actual request and response for `dog metric post`

**Comment by dabcoder** [comment]
Sorry for the delay in updating that thread and thanks for the feedback. 

The post method does not have debug logs https://github.com/DataDog/datadogpy/blob/ff4a4378c9d44df77b28773578c3ca2bfb847c5c/datadog/dogshell/metric.py#L37 nor does the submit method in the `api_client`: https://github.com/DataDog/datadogpy/blob/dcd18be574d2491930471b8660b7c962bfa93527/datadog/api/api_client.py#L48. 
Feel free to add details to this thread should you want to follow up with us but I'm going to close this issue for now, as we're not currently planning on implementing this at the moment.
