### ISSUE TITLE
Threadstats emits everything as Gauge

### ISSUE THREAD

**Issue by mottaquikarim** [DataDog/datadogpy#245]
It appears that all metrics sent via ThreadStats are being sent as type "Gauge".

In `_get_aggregate_metrics` method of `datadog/threadstats/base.py`, all metrics that are passed are sent as [`MetricType.Gauge`](https://github.com/DataDog/datadogpy/blob/master/datadog/threadstats/base.py#L340). The `flush` method will when appropriate call `_get_aggregate_metrics`, which seems to hardcode the `Gauge` MetricType. Furthermore, on DD *Metric Explorer* page, when inspecting a custom metric it appears that under the `Metadata` field, the *Metric Type* is always set to *gauge*.

This appears to be a bug, `_get_aggregate_metrics` should leverage the `stats_tag` property of classes defined in `datadog/threadstats/metrics.py` to determine the correct `MetricType` property to pass.

**Comment by thenano** [comment]
Looks like this issue is fixed with release 0.19.0?

**Comment by gzussa** [comment]
Closing this issue since it seems to be fixed
