### ISSUE TITLE
Cannot init datadog with just a Hostname and Port 

### ISSUE THREAD

**Issue by emfleisch** [DataDog/datadogpy#246]
Datadog-python requires initialize to have an API_KEY and APP_KEY. 
I have a DD/statsd forwarder running that I already use and can enable in my node modules through hot-shots via url:port (where no api_key is necessary). Looking for a way to keep that paradigm into my Python code. 

https://github.com/brightcove/hot-shots/blob/master/README.md

**Comment by mycaule** [comment]
Hello @emfleisch have you found a solution to your problem?
I think the issue I opened in #291 is similar.

**Comment by dabcoder** [comment]
@emfleisch Sorry for the long delay in responding. Just to make sure I understood the situation correctly, you'd like to do what is described in @mycaule comment here: https://github.com/DataDog/datadogpy/issues/291#issue-357173852, without specifying any keys, correct?

**Comment by dabcoder** [comment]
Closing this for now since there aren't any new responses in this thread but feel free to reopen this if need be. Thanks!
