### ISSUE TITLE
Missing endpoints in Python Client

### ISSUE THREAD

**Issue by l0k0ms** [DataDog/datadogpy#247]
The following endpoints don't have a dedicated method in the Datadog python client:

* [Cancel Monitor downtimes by scopes](https://docs.datadoghq.com/api/?lang=python#cancel-monitor-downtimes-by-scope)
* [integrations API](https://docs.datadoghq.com/api/?lang=python#integrations)
* [Resolve monitor](https://docs.datadoghq.com/api/?lang=python#resolve-monitor)
* [Organization](https://docs.datadoghq.com/api/?lang=python#organizations)
* [Usage](https://docs.datadoghq.com/api/?lang=python#usage-metering)

**Comment by gzussa** [comment]
Thanks, I am adding this to our backlog. Closing this card since the scope is too large for being an issue.
