### ISSUE TITLE
EventStream API 

### ISSUE THREAD

**Issue by myavalka** [DataDog/datadogpy#251]
Any chance there is the ability to add host arguments to the Query Event Stream call? The functionality is there in the UI but not in the actual API call.

**Comment by dabcoder** [comment]
Apologies for the long delay in updating this thread. It is indeed possible. We're not specifying any mandatory argument in the `query` method:

https://github.com/DataDog/datadogpy/blob/583bc0e9a1f939a32d21df2e7797e43554954198/datadog/api/events.py#L64.

So you can append a `host` parameter to filter by host:

```
end_time = time.time()
start_time = end_time - 100

(api.Event.query(
    start=start_time,
    end=end_time,
    priority="normal",
    host="<hostname>",
    unaggregated=True
)
```
