### ISSUE TITLE
Remove 'simplejson' as a required dependency

### ISSUE THREAD

**Issue by crccheck** [DataDog/datadogpy#265]
Hi. I just ran into the same problem outlined in this issue: https://github.com/requests/requests/issues/3052
> I've recently run into an issue where another library installed simple-json and because the requests library defaults to it if available, it caused all of our json requests to fail due to a decoding problem.

My opinionated summary of that thread is that in 2018, there's no reason to use `simplejson` anymore because:
* If people cared about performance, they'd use [ujson](https://docs.micropython.org/en/latest/pyboard/library/ujson.html)
* Python versions that didn't have `json` in the standard lib have long fallen off support grids
* simple is better than complex

Since `datadog` [already has logic to fall back](https://github.com/DataDog/datadogpy/blob/07ca80a5eb268306dd4cb5a4fb748bd8e94401ac/datadog/util/compat.py#L102) to the standard lib's `json`, it could simply remove `simplejson` from `setup.py` (probably for Python 2 too) and document that `simplejson` will be used if it's installed.

https://github.com/DataDog/datadogpy/blob/master/setup.py#L12

What do you think? Removing simplejson could simplify this project

**Comment by brianblocker** [comment]
We are also running into an issue with simplejson as a dependency. Please remove!

**Comment by kapilt** [comment]
+1, simplejson hasn't really been needed for a number of years, its been in the stdlib since 2.7, and 2.6 has been out of even security fix support for at least 3 years. https://snarky.ca/stop-using-python-2-6/.. if you still want to reporting rhel6 users, then do it only if the stdlib import fails.
