### ISSUE TITLE
import pdb left in 0.2.1 release, doesn't seem to be in repo

### ISSUE THREAD

**Issue by benweatherman** [DataDog/datadogpy#27]
I tried to `pip install datadog==0.2.1` and run our test suite.

This statement appears on line 179 of dogstatsd/base.py
```py
import pdb; pdb.set_trace()
```

https://pypi.python.org/packages/source/d/datadog/datadog-0.2.1.tar.gz#md5=45dd40f381a4b019c91fafc7d4ae284a

That code doesn't appear to be in the current master branch https://github.com/DataDog/datadogpy/blob/master/datadog/dogstatsd/base.py#L176-L186

Can you cut a new release without this debugging statement in there?

**Comment by yannmh** [comment]
My mistake ! Thanks @benweatherman for notifying it.
