### ISSUE TITLE
Hosts api endpoint not avail in 0.21?

### ISSUE THREAD

**Issue by Martiflex** [DataDog/datadogpy#278]
https://cl.ly/2M1M1X3o2y12

```
➜  pip show datadog | grep Version
Version: 0.21.0
➜  python -c "from datadog import api; api.Hosts.search()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Hosts'
```

I'm doing the docs example: https://docs.datadoghq.com/api/?lang=python#search-hosts

**Comment by nmuesch** [comment]
Hey @Martiflex Sorry for the delay here. I installed datadogpy 0.21.0 and was able to run `api.Hosts.search()` are you still encountering this issue?

**Comment by Martiflex** [comment]
I hadn't tested this since last year.

Just retested it and I don't get the same error anymore.

Happy to get this closed, thanks for your review.
