### ISSUE TITLE
Allow use of aggregate_up and use_date_happened options to query the Event Stream

### ISSUE THREAD

**Issue by tc-danielneville** [DataDog/datadogpy#289]
In the web ui, I can add `aggregate_up=false` and `use_date_happened=true` to display unaggregated events. I have not found a way to do that with the python sdk to get a true event stream. Is that possible? If not, could that feature be added?

**Comment by jirikuncar** [comment]
It should be possible with `dog.Event.query(unaggergated=True)`.

**Comment by zippolyte** [comment]
Indeed, please use the keyword argument `unaggregated=True` when doing your query, like so 
```python
dog.Event.query(unaggregated=True)
```
