### ISSUE TITLE
Allow empty list of tags to be passed in

### ISSUE THREAD

**Issue by bbangert** [DataDog/datadogpy#29]
If an empty list of tags is passed in, a Python error about an unhashable list pops up. This is because the check for tags is faulty here:
https://github.com/DataDog/datadogpy/blob/master/datadog/threadstats/metrics.py#L134

This line should use None if tags fails to bool eval to True, not the passed in value (in this case, []).

**Comment by yannmh** [comment]
That's right, thanks for reporting @bbangert.
