### ISSUE TITLE
Wrong config file location on MacOS

### ISSUE THREAD

**Issue by berend** [DataDog/datadogpy#292]
After installing the MacOS datadog agent, the config file is located here:
```
~/.datadog-agent/datadog.yaml
```
which is simlinked to 
```
/opt/datadog-agent/etc/datadog.yaml
```

This is in line with [the agents docs](https://docs.datadoghq.com/agent/basic_agent_usage/osx/?tab=agentv6#configuration), but the python bindings seem to expect the config file in 
```
~/.datadog-agent/agent/datadog.yaml
```

The code in question is [here](https://github.com/DataDog/datadogpy/blob/d575171bf38ad5841f2fab474193e17e50fa5974/datadog/util/config.py#L81) 

Without logging set to STDOUT, there is no warning in the simplest example. Here is one with the warning:
```python
from datadog import initialize
from datadog import statsd
import logging
import sys

logging.basicConfig(format="%(message)s", stream=sys.stdout, level=logging.DEBUG)

options = {"api_key": "foo", "app_key": "bar"}

initialize(**options)
statsd.increment("python.example.test")
```
gives you
```
▶ python simple.py
No agent or invalid configuration file found
```

**Comment by gzussa** [comment]
Duplicate https://github.com/DataDog/datadogpy/issues/218
