### ISSUE TITLE
dogshell + statsd?

### ISSUE THREAD

**Issue by AlJohri** [DataDog/datadogpy#298]
hi, I have a script I want to always keep running that I turn on via a bash script. I wanted to catch if the process stopped and send an event up to datadog via the `dogshell`. we currently use statsd to talk to the datadog agent- can I do this using dogshell?

thanks!

**Comment by yannmh** [comment]
@AlJohri,

You can achieve this with the `dogwrap` CLI, e.g.
```
dogwrap ./my_script.sh
```
see https://github.com/DataDog/datadogpy/blob/master/datadog/dogshell/wrap.py#L1


or by manually instrumenting your script do send an event on failures:
```
if command ; then
    echo "..."
else
    dog event post ...
fi
```

**Comment by yannmh** [comment]
Closing this issue. Please feel free to reach out to our support team @AlJohri if you need any advice.
