### ISSUE TITLE
using datadogpy on osx via docker for mac

### ISSUE THREAD

**Issue by luck02** [DataDog/datadogpy#303]
I'm getting the following errors on initialize:
```
    datadog.initialize(api_key=datadog_api_key, app_key=datadog_app_key,
                       statsd_host="localhost", 
                       statsd_port=8125)
```
error:
```
18-10-2018:12:23:20,839 INFO     [hostname.py:59] No agent or invalid configuration file found
```

Docker agent is definitely running, the ports should be exposed properly (but i'm a bit new to using docker for mac vs. docker / docker compose on osx... much more experienced setting this stuff up on linux hosts)...  However, there's something fundamental I'm missing here about how to initialize DD.

**Comment by luck02** [comment]
I'd say this issue ties directly into: https://github.com/DataDog/datadogpy/pull/294  IE lack of documentation / expected use cases.

**Comment by dabcoder** [comment]
Sorry for the delay in updating this thread. 
This is actually tied to https://github.com/DataDog/datadogpy/pull/428. The library tries to fetch the hostname from the agent 5 configuration file. If it fails to find it, it'll display this log line. We've added an option to get rid of this line and downgraded it to `WARN` as well. 
Hope that clarifies the situation.
