### ISSUE TITLE
No wheels on PyPi

### ISSUE THREAD

**Issue by darkvertex** [DataDog/datadogpy#307]
Hey guys, could you deploy some .whl (Python wheel) files when you deploy future versions?

https://pypi.org/project/datadog/#files only has .tar.gz

pip is slower when no wheel is available because it has to generate it on its own before using the package.

**Comment by yannmh** [comment]
Thanks @darkvertex. That's something we'll do with our next release.

**Comment by darkvertex** [comment]
Great. Thanks @yannmh!

**Comment by gzussa** [comment]
Closing this since it's done
