### ISSUE TITLE
Datadog agent version 6 support

### ISSUE THREAD

**Issue by SEAPUNK** [DataDog/datadogpy#313]
Does this library support dd agent v6 (https://github.com/Datadog/datadog-agent)?

If not, are there plans to support it?

**Comment by yannmh** [comment]
Yes you can use the StatsD client with Datadog Agent 5 or 6.

**Comment by acjay** [comment]
I'm seemingly having issues with the loading of `~/.datadog-agent/datadog.yml`. It appears the library is still trying to load `~/.datadog-agent/agent/datadog.conf`.

**Comment by jadami10** [comment]
I am having the same issue as @acjay. The latest code also uses configparser which is unable to load yaml files.
