### ISSUE TITLE
Discrepancies in documentation

### ISSUE THREAD

**Issue by alexpjohnson** [DataDog/datadogpy#315]
Hey, I'm not sure if this is the right place to highlight this, but I wanted to list some discrepancies in the documentation for the monitor creation API from what gets returned.

* https://docs.datadoghq.com/api/?lang=python#create-a-monitor lists a metric monitor type as a "query alert", but I'm pretty sure the example is highlighting it as a "metric alert" value. 

* The "include_tags" option says it should come back as a boolean value, but I'm getting the string representation, so "true" instead of True.

These aren't really pressing, but figured it was worth a report. Thanks for the awesome tool!

**Comment by cswatt** [comment]
Thanks for flagging these! Both of these issues have now been resolved—metric monitors are indeed of type metric alert, and `include_tags` now returns a Boolean.
