### ISSUE TITLE
statsd_host doesn't do anything

### ISSUE THREAD

**Issue by montyz** [DataDog/datadogpy#321]
So it turns out that setting the statsd_host doesn't actually work:

```
from datadog import initialize, dogstatsd
initialize(host_name="datadog-example", statsd_host="datadog-statsd.datadog.svc.cluster.local", statsd_port= 8125, statsd_use_default_route=True)
```

But if I initialize DogStatsd directly it does work:
```
statsd=dogstatsd.base.DogStatsd(host="datadog-statsd.datadog.svc.cluster.local", port = 8125)
```
So obviously the two are not connected.

**Comment by george-miller** [comment]
thank you for posting this!  It saved me a whole lot of trouble.

**Comment by zippolyte** [comment]
Hey @montyz, @george-miller 

The parameter `statsd_host` of the `initialize`function` is actually correctly working. It's just that you have set at the same time `statsd_use_default_route` to `True`, which overrides the `statsd_host` parameter. 

See 
https://github.com/DataDog/datadogpy/blob/500e96369108eee6eef6378a64efbe2dab898f3b/datadog/__init__.py#L86-L88
and https://github.com/DataDog/datadogpy/blob/500e96369108eee6eef6378a64efbe2dab898f3b/datadog/dogstatsd/base.py#L134-L147

Closing.
