### ISSUE TITLE
Support for statsd.Pipeline

### ISSUE THREAD

**Issue by tutuca** [DataDog/datadogpy#323]
I need to "send" a number of metrics in the same event. 
I could be using multiple `gauge`s, but that is not giving me the result I wanted.
Statsd has a feature that seems to work the way I want:
https://statsd.readthedocs.io/en/v3.3/pipeline.html

Is there anything close to `statsd.Pipeline` in datadogpy?

**Comment by dabcoder** [comment]
Sorry for the delay in updating this thread. The closest thing we'd have would be sending those gauge as a `batch`: https://docs.datadoghq.com/developers/dogstatsd/high_throughput/?tab=python.

```
with DogStatsd(host="127.0.0.1", port=8125, max_buffer_size=25) as batch:
    batch.gauge('example_metric.gauge_1', 123, tags=["environment:dev"])
    batch.gauge('example_metric.gauge_2', 1001, tags=["environment:dev"])
```

Would that work for your use case?

**Comment by tutuca** [comment]
That would work, yes. Thanks for the response!
