### ISSUE TITLE
Post metic via REST API without host

### ISSUE THREAD

**Issue by xkrt** [DataDog/datadogpy#325]
Hi!

Why can't post metric without `host` tag over REST API? See: https://github.com/DataDog/datadogpy/blob/2597749787a27ac08fd5c2af0bb651ea395bdce9/datadog/api/metrics.py#L91

```
attach_host_name=True
```

[Docs on API says](https://docs.datadoghq.com/api/?lang=python#post-timeseries-points) that `host` is optional.

I want to post metric from some "serverless" environment, and every time my metrics has various `host` tag and my "Infrastructure list" page on DD web pollutes with this ephemeral hosts.

**Comment by jessegonzalez** [comment]
I see the same issue with Event.

**Comment by jirikuncar** [comment]
Related to #180
