### ISSUE TITLE
dogwrap doesn't provide any output until wrapped command completes

### ISSUE THREAD

**Issue by ddaniels888** [DataDog/datadogpy#33]
dogwrap buffers the wrapped command's stderr and stdout to a string, and only prints to stdout and stderr upon completion. Without some realtime output, it's hard to use dogwrap on long-running commands.

**Comment by ddaniels888** [comment]
Here's a snippet I've used before to grab output in realtime from subprocess, in case it's useful: https://github.com/mortardata/mortar-luigi/blob/master/mortar/luigi/mortartask.py#L496:L508

You lose differentiation between the wrapped command's stdout and stderr when you do that though, but do get realtime output. It may be possible to still subprocess.PIPE stderr and just not consume it until the process ends.

I think the timeout feature of dogwrap also makes this more comlex, as reading the wrapped command's stdout will block, and hence might require some threading to implement the timeout separately.

**Comment by yannmh** [comment]
Hey @ddaniels888, I agree it would be nice to have a some kind of realtime output.
Thanks for the snippet, I'll see how I can adapt with dogwrap.

**Comment by alq666** [comment]
@yannmh if you don't have a card for this, can you add one so that we can triage?

**Comment by yannmh** [comment]
Sure. 
Just added a card for it.

**Comment by yannmh** [comment]
Fixed in v0.4.0
