### ISSUE TITLE
Document is not updated

### ISSUE THREAD

**Issue by hitsumabushi** [DataDog/datadogpy#337]
Library document don't seem to be updated.

datadogpy supports [Hosts.search](https://github.com/DataDog/datadogpy/blob/master/CHANGELOG.md#0210--2018-06-04).
But, not documented at https://datadogpy.readthedocs.io/en/latest/. (And datadog.api.Infrastructure.sesarch is deprecated API.)

Currently, library users must read source code...

**Comment by cswatt** [comment]
Thanks! This has now been updated.
