### ISSUE TITLE
[question] can I call initialize several times?

### ISSUE THREAD

**Issue by cmdelatorre** [DataDog/datadogpy#347]
Consider the following example:

```python
from datadog import initialize, statsd
initialize(statsd_port=8001)
initialize(statsd_port=8002)
initialize(statsd_port=8003)

statsd.increment('home.page.hits')  # Is port 8003 being used here?
```

If I call `initialize` with different parameters, will the last call take effect?

**Comment by zippolyte** [comment]
Hi @cmdelatorre 

Yes the last call will take effect. With PR #386, calling initialize several time will not override other already set parameters if they are not specified in the call.
