### ISSUE TITLE
dogshell event post typo

### ISSUE THREAD

**Issue by celenechang** [DataDog/datadogpy#35]
the message doesn't show up when using `dog event post`, i think it's because the api call should have `text=message` instead of `message=message` https://github.com/DataDog/datadogpy/blob/master/datadog/dogshell/event.py#L118

**Comment by samanthadrago** [comment]
This is still an issue for me - message of the event is not posted (dog 0.3.0)

`dog --api-key {api key} --application-key {app key} event post "hello" "test message"`
->`hello ()`

**Comment by celenechang** [comment]
@samanthadrago i think this fix is in v. 0.4.0

**Comment by samanthadrago** [comment]
My bad, this is fixed in 0.4.0!
