### ISSUE TITLE
Sending to a generic statsd server

### ISSUE THREAD

**Issue by ldelossa** [DataDog/datadogpy#354]
Can I use this library to send to a generic statsd server also? I want to basically send to datadog but if connection fails fall back to a local statsd server so we do not loose metrics.

**Comment by dabcoder** [comment]
Hello @ldelossa, apologies for the delay in updating this thread. 

We currently don't support this as the `statsd_host` parameter only takes a [unique] address as value.

As a workaround, it may be possible to have two `DogStatsd` instances (the first one for Datadog and the second one for your statsd host). You could then use try/except clauses, where you would send to Datadog in the former clause and send it to your statsd server in the latter.

Let us know if you have any additional details on the use case too.
