### ISSUE TITLE
Any plan for releasing a new version?

### ISSUE THREAD

**Issue by bcho** [DataDog/datadogpy#358]
Hi, it has been 14 commits since the last 0.26.0 release, any plan for releasing a new version including these changes? The specific fix I am looking for is #349, maybe we can ship a `0.26.1` for it? (Of course, I know I can always lock to a commit, but it would be better to use a bug fix release.)

**Comment by yannmh** [comment]
Hi @bcho, we are releasing today.

**Comment by yannmh** [comment]
v0.27.0 is out. Thank you for your patience @bcho.
