### ISSUE TITLE
ImportError: cannot import name initialize

### ISSUE THREAD

**Issue by linmark333** [DataDog/datadogpy#37]
Getting this error following tutorial, datadog is installed via pip.  Unable to import "initialize".

from datadog import initialize

**Comment by yannmh** [comment]
Hi @linmark333 ,

I reckon it could be a name conflict between `datadog` package and one of your python file. Could you please try this snippet ?

``` python
import datadog
print datadog
```

and make sure, it returns the right Python module path (i.e. `/usr/local/lib/python2.7/dist-packages/...` on Linux, `/Library/Python/2.7/site-packages/...` on Mac OS X) ?

Thanks

**Comment by linmark333** [comment]
You were right, it was a name conflict.  Was trying to follow this for ansible hooks, and because it was using old datadog library, there wasn't conflict.

https://gist.github.com/alekstorm/6350729

**Comment by jpblair** [comment]
For anyone else out there...don't call your script datadog.py.  I'm dumb.
