### ISSUE TITLE
Splunk integration via dogapi: message/text does not appear in the event

### ISSUE THREAD

**Issue by tjbaker** [DataDog/datadogpy#38]
http://docs.datadoghq.com/integrations/splunk/

There are a few problems following the documentation.
1. The env variables you're referencing don't seem to exist.  This is a Splunk issue.  Resolution is to use positional arg $2, $3 etc rather than environment variables
2. the "body" of the event does not end up in the event on the site, it is empty.

```
#!/bin/bash
API_KEY= your_api_key
APP_KEY= your_application_key
dog --api-key $API_KEY --application-key $APP_KEY event post \
"Found $SPLUNK_ARG_1 events in splunk" \
"Matching $SPLUNK_ARG_2 based on $SPLUNK_ARG_5, from report $SPLUNK_ARG_4. More details at $SPLUNK_ARG_6." \
--aggregation_key $SPLUNK_ARG_3 --type splunk
```

I ended up using curl to get it all working.  Here is a working example:

```
#!/bin/bash

API_KEY=
APP_KEY=


# http://docs.datadoghq.com/api/
#
# http://docs.splunk.com/Documentation/Splunk/6.2.2/Alert/Configuringscriptedalerts
#
#  Arg Value
#  1   Number of events returned
#  2   Search terms
#  3   Fully qualified query string
#  4   Name of report
#  5   Trigger reason
#  6   Browser URL to view the report.
#  7   Not used for historical reasons.
#  8   File in which the results for the search are stored. Contains raw results.


curl  -X POST -H "Content-type: application/json" \
-d '{
      "title": "Found '"$1"' events in splunk",
      "text": "Matching '"$2"' based on '"$5"', from report '"$4"'. More details at '"$6"'.",
      "aggregation_key": "'"$3"'",
      "source_type_name": "splunk"
  }' \
https://app.datadoghq.com/api/v1/events?api_key=$API_KEY&application_key=$APP_KEY
```

**Comment by yannmh** [comment]
Hi @tjbaker,

Thanks a lot for reporting this issue.  I'll update the Splunk integration documentation according to your feedback.

About point 2, it is probably related with https://github.com/DataDog/datadogpy/pull/36. 
A new release of `datadogpy` is about to be released, and will contain this fix.

Thanks again

**Comment by yannmh** [comment]
Seems like latest Splunk documentation still recommands the usage of [$SPLUNK_ARG_](http://docs.splunk.com/Documentation/Splunk/6.2.4/Alert/Configuringscriptedalerts) environment variables. Could it be a transient issue ?

I am closing the issue. Please feel free to re-open if it happens again.

Thanks again for reporting @tjbaker.
