### ISSUE TITLE
Dogwrap uses python 2 print syntax

### ISSUE THREAD

**Issue by Matt343** [DataDog/datadogpy#384]
The `datadog.dogshell.wrap` module uses Python 2 style `print >> ` syntax throughout, which breaks when running `dogwrap` on Python 3. More generally, it's unclear whether or not `dogwrap` is a supported feature in the current release.

**Comment by zippolyte** [comment]
Hey @Matt343, thanks for reporting.

This was indeed an oversight, and was fixed in #379 

There will be a new release of datadogpy really soon.
