### ISSUE TITLE
Encoding issue on install (0.29.0)

### ISSUE THREAD

**Issue by ningirsu** [DataDog/datadogpy#390]
Hi,

With the last version of the datatog agent (1.29.0) we have an issue during the setup.py

```
 Collecting datadog (from SqBackEnd==0.1)
   Using cached https://files.pythonhosted.org/packages/0c/19/6d13dd5685afe431fd156608bd07ae425d61c7059d6c50d3806418508879/datadog-0.29.0.tar.gz
     ERROR: Complete output from command python setup.py egg_info:
     ERROR: Traceback (most recent call last):
       File "<string>", line 1, in <module>
       File "/tmp/pip-install-3hq540_6/datadog/setup.py", line 24, in <module>
         long_description=get_readme_md_contents(),
       File "/tmp/pip-install-3hq540_6/datadog/setup.py", line 8, in get_readme_md_contents
         long_description = f.read()
       File "/tmp/virtual_env_BackEnd__3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
         return codecs.ascii_decode(input, self.errors)[0]
     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3377: ordinal not in range(128)
```

We can probably fix it by setting up some env variable on our side, but you may want to fix this ;)

**Comment by ningirsu** [comment]
Would also be good to generate wheel for packaging, it will prevent this kind of issue

**Comment by Alphadash** [comment]
I noticed you were working on this too, but taking a different approach.
I looked in the README.md file and there is a non-ASCII apostrophe, when I replaced it I can build the module locally.

https://github.com/DataDog/datadogpy/pull/392

**Comment by fimmtiu** [comment]
+1; this broke a CI build for us that tries to install datadog through pip. Solved it by pinning our app to 0.28.0.

**Comment by andrewmwilson** [comment]
It would be nice to get this looked at considering it's pretty badly broken and the fix is trivial.

**Comment by ningirsu** [comment]
ping @nmuesch Maybe you did not see this error but it can impact a lot of people. You just need to merge one of these PRs: (better to merge both)
https://github.com/DataDog/datadogpy/pull/391
https://github.com/DataDog/datadogpy/pull/392

**Comment by zippolyte** [comment]
Just merged the two PRs, closing.
Thanks for reporting and posting a fix.
