### ISSUE TITLE
[feature] dogwrap should report `duration` as a metric

### ISSUE THREAD

**Issue by miketheman** [DataDog/datadogpy#4]
When using the CLI tool `dogwrap` in conjunction with a utility like `cron`, we get the event output on the Event Stream which helps us determine success vs failure.

Adding a metric for `duration` for the event, which is already calculated and placed in the Event Title would allow trending this particular event over time, and potentially alerting on the value.

**Comment by dabcoder** [comment]
Closed by #506

**Comment by miketheman** [comment]
Thanks @dabcoder !!
