### ISSUE TITLE
Metrics API call fails with TypeError (0.29.1)

### ISSUE THREAD

**Issue by aamangeldi** [DataDog/datadogpy#400]
Hello,
Since the release of 0.29.1, our code that makes an API call to `Metric.send()` started failing with the following error:
```
/databricks/python/lib/python3.5/site-packages/datadog/api/metrics.py in send(cls, metrics, attach_host_name, **single_metric)
     89             raise KeyError("'points' parameter is required")
     90 
---> 91         return super(Metric, cls).send(attach_host_name=attach_host_name, **metrics_dict)
     92 
     93     @classmethod

/databricks/python/lib/python3.5/site-packages/datadog/api/resources.py in send(cls, attach_host_name, id, **body)
     76         if id is None:
     77             return APIClient.submit('POST', cls._resource_name, api_version, body,
---> 78                                     attach_host_name=attach_host_name)
     79 
     80         path = '{resource_name}/{resource_id}'.format(

/databricks/python/lib/python3.5/site-packages/datadog/api/api_client.py in submit(cls, method, path, api_version, body, attach_host_name, response_formatter, error_formatter, **params)
    160             if response_obj:
    161                 for response in response_obj:
--> 162                     response['response_headers'] = response_headers
    163 
    164             if response_formatter is None:

TypeError: 'str' object does not support item assignment
```

Downgrading to 0.29.0 solves the problem for us, but this is still an issue.
Also mentioned in #397.

We're using Python 3.5.2

**Comment by rouge8** [comment]
This also broke the Event api, `datadog.api.Event.create()` fails with the same error.

**Comment by nmuesch** [comment]
Hey, very sorry for the inconvenience here. We're looking into this, thanks for the report!

**Comment by nmuesch** [comment]
Hey @aamangeldi and @rouge8 We've just pushed out 0.29.2 which reverts the response header changes that went out with 0.29.0 and reverts the attempted fix of 0.29.1 to mitigate this issue. 

Apologies for the inconvenience here. Please let me know if you continue to hit this issue on 0.29.2

**Comment by aamangeldi** [comment]
@nmuesch thanks for the quick response!

**Comment by agottlie** [comment]
Closing this issue for now due to the release of 0.29.2, but please feel free to reach back out to us at support@datadoghq.com if you run into any additional issues.
