### ISSUE TITLE
API_HOST should be manipulated as an URL and not as a string

### ISSUE THREAD

**Issue by octplane** [DataDog/datadogpy#411]
This creates errors when changing the host to something with a trailing `/`

https://github.com/DataDog/datadogpy/blob/7fb486f53e6992e088d27cc5d644428681affdd4/datadog/api/api_client.py#L121

**Comment by dabcoder** [comment]
Example if `api_host` is `api.datadoghq.com/`, it will result in a double `//`: `api.datadoghq.com//api/...`.
