### ISSUE TITLE
Constant error: "datadog.api: No agent or invalid configuration file found"

### ISSUE THREAD

**Issue by apenney** [DataDog/datadogpy#416]
I'm getting a lot of errors like:

```
2019-07-03 16:20:12,233 [INFO:140620589405376:26627] datadog.api: No agent or invalid configuration file found
```

After digging in a bit I realized in `datadog/util/config.py` we have:

```def _unix_config_path():
    path = os.path.join('/etc/dd-agent', DATADOG_CONF)
    if os.path.exists(path):
        return path
    raise PathNotFound(path)
```

However, on my machines (AWS Linux 2):

```
# ls -lad /etc/datadog-agent/
drwxr-xr-x 4 dd-agent dd-agent 187 Jun 10 19:04 /etc/datadog-agent/
```

Does it make sense to check for both paths, change this, etc? Something definitely feels wrong here.

**Comment by dabcoder** [comment]
Thanks for reporting this @apenney, we'll be looking into this and get back to you, thanks for the details.

**Comment by dabcoder** [comment]
We've taken care of this in #428 (downgrade to warning and add an option hostname_from_config=False) to turn this off completely - it will be available in the next release, and we aim to deprecate this feature in the future.

**Comment by bkabrda** [comment]
Closing this issue now, see @dabcoder's comment above on how to get rid of these errors.
