### ISSUE TITLE
"Hostname: localhost is local" log.warning but only from within an rq.Worker in a Flynn container.

### ISSUE THREAD

**Issue by jasonrubenstein** [DataDog/datadogpy#422]
```Hostname: localhost is local (/.heroku/python/lib/python*/site-packages/datadog/util/hostname.py:is_valid_hostname)```

The warning is logged _only_ from within the task running in an rq worker, utilizing gevent, in a Flynn job. 

When I submit a job to the worker and call `datadog.util.hostname.get_hostname()`, the response is the correct hostname and not "localhost". 

I'm still looking into this, but any insight would be great.

**Comment by dabcoder** [comment]
@jasonrubenstein Is this still an issue (you closed this a few days ago, but just wanted to follow up in case we would need to investigate)?

**Comment by jasonrubenstein** [comment]
Yes, still an issue.  I opened a Zendesk ticket for it, as well.
