### ISSUE TITLE
Failed to send traces to Datadog Agent at <ddtrace.api.API object at 0x7f84922e2908>: ConnectionRefusedError(111, 'Connection refused')

### ISSUE THREAD

**Issue by debugger22** [DataDog/datadogpy#430]
This issue keeps on coming intermittently but in huge numbers almost maxing out my Sentry quota.

ddtrace==0.27.1
Django==2.0.8
Python 3.6

Sentry error: https://sentry.io/share/issue/c6f8627d4ab3454090b76cebb87a70fb/

**Comment by dabcoder** [comment]
@debugger22 looks like you're referring to https://github.com/DataDog/dd-trace-py and not this repository. Can you follow up over there or contact support@datadoghq.com with an overview of the issue you're experiencing?
