### ISSUE TITLE
DogStatsd is not thread-safe when using buffer

### ISSUE THREAD

**Issue by jd** [DataDog/datadogpy#439]
If I'm reading the code correctly, the class `DogStatsd` is not thread-safe when using a buffer.

`open_buffer` does the following: `self.buffer = []`
Which means that if you have 2 threads opening a buffer at the same time, they will override each other.

The `open_buffer` class should return a different object that should be used as the buffer object.

**Comment by jd** [comment]
Just to add an example of what I mean, `redis-py` has a nice design where they return a `Pipeline` object when you call `client.pipeline()`. That's something that'd work fine in that case.
https://redis-py.readthedocs.io/en/latest/#redis.Redis.pipeline

**Comment by hush-hush** [comment]
Hi @jd,

Thanks for opening this issue. We're currently planning some ground work on the Python DogStatsD client. This is definitely on the list of things to improve/change. I can't give you any estimation about when this will be available but I'll be sure to update this issue !

**Comment by komuw** [comment]
could use `collections.deque` which are documented as thread-safe and can act as a drop in replacement for list

https://docs.python.org/3.7/library/collections.html#collections.deque
