### ISSUE TITLE
Tags with commas incorrectly treated as multiple tags

### ISSUE THREAD

**Issue by felixc** [DataDog/datadogpy#485]
It appears that commas in tags are incorrectly treated as tag separators when sent over the API. This results in a list of tags like `["foo:bar, baz", "quux:quuz, frob"]` being misinterpreted as `["foo:bar", "baz", "quux:quuz", "frob"]`.

Although I understand that the API uses commas to separate values in your serialization format, I believe that since we are passing in a clear list structure, this behaviour is unexpected and incorrect. I would hope that commas within tags would be escaped and treated as just commas; or if that's not possible, ignored/replaced with a "safe" character.

The relevant lines may be these ones (but I'm not familiar with the codebase so I can't say for sure): https://github.com/DataDog/datadogpy/blob/09c0a953d47675777ab57f3840b4b04ef378ff4d/datadog/api/api_client.py#L134-L136

I would suggest also documenting this restriction here: https://docs.datadoghq.com/tagging/#defining-tags

For what it's worth, I believe this was changed in the Ruby client some time ago: https://github.com/DataDog/dogstatsd-ruby/blob/master/CHANGELOG.md#tags

**Comment by dabcoder** [comment]
Thanks for reporting this @felixc. This should be solved with #489. Let us know if this still causes issues, in which case you can reopen this thread.
