### ISSUE TITLE
Can't handle exceptions thrown by threadstats

### ISSUE THREAD

**Issue by trygvebw** [DataDog/datadogpy#490]
It would be very useful to be able to handle any exceptions thrown by threadstats, including HTTPError but also other exceptions, instead of threadstats just silently swallowing most exceptions. Currently this doesn't seem to be possible; correct me if I'm wrong. Ideally I'd be able to provide threadstats with an error handler function that is invoked every time threadstats throws an exception.

**Comment by jeremy-lq** [comment]
@trygvebw Apologies for the delay. Please open a support ticket so we can properly track this feature request. Thanks.
