### ISSUE TITLE
datadogpy's host overrides datadog agent's one

### ISSUE THREAD

**Issue by fTrestour** [DataDog/datadogpy#492]
Hi!

I had an issue with datadogpy adding a `host` key in my logs with a different value from the one set by my datadog agent.
I solved it by turning of the `host` reserved attribute in my datadog logs dashboard, however being able to disable this behaviour when initialising datadogpy would be great!

Is such a feature planned? Is it already available and I missed something in the docs?

**Comment by zippolyte** [comment]
Hello Fabien,

So if I understand correctly, you would like datadogpy to not set any hostname at all right ?
To do so, you can use the `attach_host_name=False` argument to the `send` (cf https://github.com/DataDog/datadogpy/pull/383 that was released in 0.29.0).
Would that solve your issue ?

You could also set the same hostname as your agent by specifying `host_name` in the `initialize` function.

**Comment by fTrestour** [comment]
> So if I understand correctly, you would like datadogpy to not set any hostname at all right ?

Yes, exactly.

> To do so, you can use the attach_host_name=False argument to the `send`

Interesting, that seems close to what I need. But is that limited to a single event? I'd like it to affect all of my logs

Thanks for your quick answer!

**Comment by zippolyte** [comment]
Yeah you would have to add this argument to every call sending metrics or events where you don't want a host attached.

Is that an issue for you ?

**Comment by dabcoder** [comment]
Closing this issue for now. Feel free to reopen this if needed @fTrestour.
