### ISSUE TITLE
Is it thread safe?

### ISSUE THREAD

**Issue by sebest** [DataDog/datadogpy#5]
Hello,

Could you add informations about thread safeness , i'm specifically interested about the statsd variable.

thanx

**Comment by yannmh** [comment]
Thanks @sebest for your feedback. 

We just released `datadogpy` v0.2.0 which includes thread safety specific fixes, tests and a notice on the `README` page. 
https://github.com/DataDog/datadogpy/blob/master/CHANGELOG.md#020--20150331

To answer your question: `DogStatsd` (all versions) and `ThreadStats` (> v0.2.0) are both thread safe :boom:
