### ISSUE TITLE
constant_tags parameter

### ISSUE THREAD

**Issue by bharel** [DataDog/datadogpy#523]
According to datadog docs, you're able to pass `statsd_constant_tags` into the `initialize()` function.

Unfortunately, the latest code in PyPi isn't synchronized with the GitHub code.
Although both have the same __version__ tag, the code in PyPi does not have the constant tags parameter.
The `**kwargs` parameter further masks the issue, and doesn't show an error when you pass a non-existing parameter.

Version in use - 0.33.0.

In total there are 3 issues that need to be addressed:
1. Datadog setup.py in the main branch and PyPi should have different version tags (master being 1 forward). Otherwise the code is misleading.
2. Datadog official read-the-docs should have the documentation corresponding to the latest **PyPi** version. Otherwise the documentation isn't related to the current code users are running.
3. kwargs parameter should be addressed. Current implementation masks errors. I'm not sure if we can solve this one.

Thanks,
Bar Harel @ BioCatch

**Comment by ian28223** [comment]
@bharel Along with the release of 0.34.0, `statsd_constant_tags` is now documented and should also reflect what is seen in readthedocs. Let us know if this is still not the case for you

**Comment by zippolyte** [comment]
Hello @bharel,

Indeed the versions on master did not match what could be downloaded from PyPI. We've now changed our release process to take that into account, and everything should be synchronized correctly from now on.

Thanks for raising this issue with us.
