### ISSUE TITLE
Telemetry adding to custom metric count

### ISSUE THREAD

**Issue by nishkala** [DataDog/datadogpy#528]
**Describe the bug**
The telemetry added in version 0.34 (pr: https://github.com/DataDog/datadogpy/pull/505) is reporting as custom metrics if the client is set to use a namespace for all metrics. 

**To Reproduce**
1. Initialize the DogStatsd client and set the `namespace` parameter. 
2. Emit any metrics
3. Metric appears as a custom metric on the Account Usage page. 

**Expected behavior**
Telemetry metrics are not namespaced and do not appear as custom metrics.

**Environment and Versions (please complete the following information):**
A clear and precise description of your setup:
  - Datadogpy version 0.34

**Comment by hush-hush** [comment]
Hi @nishkala,

Thanks for opening this issue. We reverted the telemetry PR for now and publish 0.34.1. Please update your datadog-py to this version.

The telemetry feature will be added back soon without adding the namespace.
