### ISSUE TITLE
DataDog API Client Returning Asterisks as tag when no such tag exists in UI

### ISSUE THREAD

**Issue by Kevin-Molina** [DataDog/datadogpy#535]
**Describe the bug**
When using the Python Datadog client to request a list of monitors, an Asterisk appears as a tag, but no such tag exists on the UI.

**To Reproduce**
Make a request using the client e.g. `client.Monitor.get_all()` and notice many of the monitors Tag field will have an asterisk in it, despite no such tag existing on the UI.

**Expected behavior**
API response is 1:1 with the UI

**Environment and Versions (please complete the following information):**
A clear and precise description of your setup:
Tried on client 0.29 and the latest version (0.34?)

**Additional context**

**Comment by zippolyte** [comment]
Hey @Kevin-Molina,

Can you please provide an example output of what you get ? 
I can't seem to reproduce on my end, the `tags` field is an empty array when there are no tags on my monitors.

**Comment by Kevin-Molina** [comment]
Hi @zippolyte, we've got two tags set of the form `'foo:bar'`. These show up on the UI, but when yanking them down I see the response lists a third so my response looks like:
`"tags": ['*','foo:bar', 'biz:baz']

Looks to be an issue with the API. I assume I'll need to reach out to the Datadog team over email to resolve it as their API doesn't seem to have a public github page for issues.

**Comment by zippolyte** [comment]
Yes, please reach out to support@datadoghq.com.

This doesn't appear to be an issue with the python client itself, so I'm going to close this issue then.

Thanks
