### ISSUE TITLE
ImportError: No module named datadog_checks.base

### ISSUE THREAD

**Issue by ypoplavs** [DataDog/datadogpy#536]
Library `datadog_checks.base` cannot be imported anymore, however it worked perfectly fine about two weeks ago.

I am trying to create a custom Datadog Agent check using Python script. However, it keeps giving me the following error: 

` from checks import AgentCheck
ImportError: No module named checks`

I tried to import `datadog_checks.checks` module as well but all to no avail. The installation of library from sources did not help either. 

Datadog Version: v6.16.1

Please let me know if you need more information.

**Comment by zippolyte** [comment]
Hey @ypoplavs,

Looks like your on the wrong repository, you might be looking for https://github.com/datadog/integrations-core instead

**Comment by ypoplavs** [comment]
Thank you for such a quick reply.

I will submit an issue there.
