### ISSUE TITLE
AttributeError: module 'datadog' has no attribute 'statsd'

### ISSUE THREAD

**Issue by mabodx** [DataDog/datadogpy#539]
**Describe the bug**
I just pip3 install the datadog and  try to test the following code and get the error.
```
import datadog

datadog.statsd.increment(
            'example_metric.increment', tags=["environment:dev"])



```
Error:
```
AttributeError: module 'datadog' has no attribute 'statsd'
```

![image](https://user-images.githubusercontent.com/4045116/75093310-629e2c80-55bb-11ea-8ba1-99e5a38eba4d.png)

![image](https://user-images.githubusercontent.com/4045116/75093316-6df15800-55bb-11ea-8e9b-47979939b44a.png)

**Comment by ofek** [comment]
Don't execute the file directly, or rename it

**Comment by jd** [comment]
The fact that your file is named `datadog` makes Python import your file, not the module.

**Comment by jirikuncar** [comment]
@mabodx you can find more information about module imports in [Python documentation](https://docs.python.org/3/tutorial/modules.html#the-module-search-path).
