### ISSUE TITLE
Metric value

### ISSUE THREAD

**Issue by arunyadav19** [DataDog/datadogpy#553]
Hi,

Is there any way I can export value of a metric (value of a widget on a dashboard ) into csv or any other format so that I can use that data in some other apps?

**Comment by zippolyte** [comment]
Yes, you can do a metric query similar to what's in your widget.
See     
```python
def query(cls, **params):
        """
        Query metrics from Datadog

        :param start: query start timestamp
        :type start: POSIX timestamp

        :param end: query end timestamp
        :type end: POSIX timestamp

        :param query: metric query
        :type query: string query

        :returns: Dictionary representing the API's JSON response

        *start* and *end* should be less than 24 hours apart.
        It is *not* meant to retrieve metric data in bulk.

        >>> api.Metric.query(start=int(time.time()) - 3600, end=int(time.time()),
                             query='avg:system.cpu.idle{*}')
        """
```

**Comment by gzussa** [comment]
Closing this issue since it seems to be answered. Feel free to contact our support for any other questions. See our [contributing.md guide](https://github.com/DataDog/datadogpy/blob/master/CONTRIBUTING.md#reporting-a-bug---requesting-a-feature---github-issues).
