### ISSUE TITLE
dog CLI tries to create .dogrc file twice (after first attempt succeeds)

### ISSUE THREAD

**Issue by cee-dub** [DataDog/datadogpy#580]
**Describe the bug**
Running `dog` without a `~/.dogrc` file goes through an interactive process to create the file with API credentials. When accepting the default for `[Y/n]` by pressing return or enter without typing `y`, it writes the file then immediately complains that the file doesn't exist and tries to do it again. The second attempt produces a stack trace.

It functions correctly if a `y` is typed in before pressing return or enter.

**To Reproduce**
1. Install the datadog client: `pip install datadog`
2. 
```console
$ dog search query "index:main"
/Users/cameron/.dogrc does not exist. Would you like to create it? [Y/n]
What is your api key? (Get it here: https://app.datadoghq.com/account/settings#api) [redacted]
What is your application key? (Generate one here: https://app.datadoghq.com/account/settings#api) [redacted]
Wrote /Users/cameron/.dogrc
/Users/cameron/.dogrc does not exist. Would you like to create it? [Y/n]
What is your api key? (Get it here: https://app.datadoghq.com/account/settings#api) [redacted]
What is your application key? (Generate one here: https://app.datadoghq.com/account/settings#api) [redacted]
Traceback (most recent call last):
  File "/usr/local/bin/dog", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/datadog/dogshell/__init__.py", line 79, in main
    config.load(args.config, args.api_key, args.app_key)
  File "/usr/local/lib/python3.7/site-packages/datadog/dogshell/common.py", line 73, in load
    config.add_section('Connection')
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 1205, in add_section
    super().add_section(section)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 658, in add_section
    raise DuplicateSectionError(section)
configparser.DuplicateSectionError: Section 'Connection' already exists
```

**Expected behavior**
Accepting the default (just pressing return or enter) should work the same as typing a `y` and then pressing return or enter.

**Screenshots**
N/A

**Environment and Versions (please complete the following information):**
A clear and precise description of your setup:
  - version for this project in use: `dog 0.37.1`
  - services, libraries, languages and tools list and versions: `Python 3.7.7`, `pip 20.0.2 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)`

**Additional context**

**Comment by zippolyte** [comment]
Fixed in #582
