### ISSUE TITLE
Possible race condition in _flush_buffer

### ISSUE THREAD

**Issue by NorthIsUp** [DataDog/datadogpy#601]
The internal buffer is not cleared until after a yield to io, it is possible for another thread to attempt to flush the same buffer.

```py
    def _flush_buffer(self):
        self._send_to_server("\n".join(self.buffer)) # <-- do io, might yield greenlet/thread
        self._current_buffer_total_size = 0
        self.buffer = []
```

**Expected behavior**
no race conditions plz!

**Environment and Versions (please complete the following information):**
0.39.0

**Comment by jd** [comment]
See https://github.com/DataDog/datadogpy/issues/439
