### ISSUE TITLE
Send metric with unit

### ISSUE THREAD

**Issue by ocervell** [DataDog/datadogpy#606]
Is there a way we can set the unit to metrics written with `statsd.gauge` or `statsd.histogram` ? I want to create a custom histogram with latencies in `ms` but there is no way to set the type AFAIK. Does statsd support it ? Do we have a way to add it as a tag `unit: ms` and DD API would understand it ?

**Comment by therve** [comment]
Hi,

For now the protocol won't support it. The recommended approach is to use the metrics metadata API separately. You can either use the python client directly, or another tool like Terraform to setup your various metrics. Thanks.
