### ISSUE TITLE
module initialization error: name 'unicode' is not defined when upgrading from 0.37.0 to 0.37.1

### ISSUE THREAD

**Issue by timothy-haak** [DataDog/datadogpy#610]
Hi, 

I am importing the Datadog libraries in an AWS Lambda function with Python 3.6. 0.37.0 works fine but anything > than 0.37.0 returns module initialization error: name 'unicode' is not defined. The behavior persists for Python 3.7 and 3.8. 

Example code:

```
from datadog import initialize, api
import time

print("foo")
```

**Comment by therve** [comment]
Thanks for your report. Do you have more details? Is there a traceback?

The only reference to unicode we have is here: https://github.com/DataDog/datadogpy/blob/30fcb30dfd5a29ade66270953a3f950787f20449/datadog/util/compat.py#L50 which is behind a sys.version check. Can you give your sys.version in theses scenarios?

**Comment by timothy-haak** [comment]
Hi, 

I added traceback for more info and got sys.version when importing 0.37.1.

```
Traceback (most recent call last):
  File "/var/task/lambda.py", line 4, in lambda_handler
    from datadog import initialize, api
  File "/var/task/datadog/__init__.py", line 17, in <module>
    from typing import Any, List, Optional
  File "/var/task/typing.py", line 782, in <module>
    AnyStr = TypeVar('AnyStr', bytes, unicode)
NameError: name 'unicode' is not defined
```
sys.version returns
```
3.6.12 (default, Sep 21 2020, 14:12:50) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

**Comment by therve** [comment]
So it looks like the error is coming from your `typing` module being outdated. Please trying to upgrade to a more recent version. Thanks.

**Comment by timothy-haak** [comment]
The Typing module is only installed when installing Datadog module > 0.37.0. When the Typing module is installed by installing the Datadog module > 0.37.0 it is the latest Typing modulev3.7.4.3. I am using `pip install datadog` as explained in the documents.

**Comment by therve** [comment]
typing 3.7.4.3 doesn't contain the line in your traceback. Furthermore, typing is only required for python 3.4, as specified in the setup.py. Can you try to remove altogether?

**Comment by timothy-haak** [comment]
I deleted both typing.py from the root directory and the typing3.7.4.3 directory. 
```
Traceback (most recent call last):
  File "/var/task/mp-ops-ebs-reprocessor-lambda.py", line 4, in lambda_handler
    from datadog import initialize, api
  File "/var/task/datadog/__init__.py", line 17, in <module>
    from typing import Any, List, Optional
ImportError: bad magic number in 'typing': b'\x03\xf3\r\n
'```

**Comment by therve** [comment]
That happens when you have pyc files that don't match your python version. Try to find any `typing.pyc` files and delete them.

**Comment by timothy-haak** [comment]
I am using Teamcity to do `pip install datadog`, zip the contents, and upload to AWS. Turns out .pyc files do not show up in the AWS Lambda console. I was able to remove the typing.pyc file and re-upload to AWS Lambda and it works now. Thank you for your help.
