### ISSUE TITLE
Add Log-queries to api 

### ISSUE THREAD

**Issue by rynmccrmck** [DataDog/datadogpy#611]
**Note:** 
Currently trying to extract large number of logs that match a given query.  We need to iterate over the 1000 limit imposed and it seems as though this is the only endpoint available.

I can take a stab at implementing unless there are concerns.

**Is your feature request related to a problem? Please describe.**
Need to extract logs over 1k limit and paginate over nextLogId.  No ability to do this via events.

**Describe the solution you'd like**
Implement LogQuery class to return list of logs: https://docs.datadoghq.com/api/v1/logs/#get-a-list-of-logs

**Describe alternatives you've considered**
Currently using requests to handle this.

**Comment by therve** [comment]
Hello,

Support for new APIs is implemented in the https://github.com/DataDog/datadog-api-client-python repository. I believe it already contains what you need. We haven't made the first release, but it should happen soon. Could you check if that works for you? Thanks.

**Comment by rynmccrmck** [comment]
Thanks @therve! Will take a look

**Comment by rynmccrmck** [comment]
Any idea on estimated time to release?

**Comment by rynmccrmck** [comment]
Closing this as it is implemented in https://github.com/DataDog/datadog-api-client-python

**Comment by therve** [comment]
Thanks for checking!

> Any idea on estimated time to release?

I don't want to set expectations, but I hope we'll cut a first beta in the next few weeks if nothing major is found. If this works for you this is a good data point :).
