### ISSUE TITLE
Event Create Text Does Not Respect Markdown

### ISSUE THREAD

**Issue by mencarellic** [DataDog/datadogpy#614]
**Describe the bug**
When using `datadog.api.Event.create` with markdown in the text parameter, it is not rendered in the Datadog event stream.  The documentation for the API [here](https://docs.datadoghq.com/api/v1/events/#post-an-event) notes that markdown is supported in the text field.

**To Reproduce**
Running the following code: 
```python
>>> import datadog
>>> datadog.initialize()
>>> ddEvent = datadog.api.Event.create(title='Testing', text="```This is a code block```", alert_type='info', tags=[])
>>> ddEvent
{'status': 'ok', 'event': {'id': 5686782223259902417, 'title': 'Testing', 'text': '```This is a code block```', 'date_happened': 1603221500, 'handle': None, 'priority': None, 'related_event_id': None, 'tags': [], 'url': 'https://app.datadoghq.com/eve
nt/event?id=5686782223259902417'}}
```

Returns this event:
```text
Testing
```This is a code block```
```

**Expected behavior**
I'd expect to see the event render the code block appropriately.

**Screenshots**
![image](https://user-images.githubusercontent.com/38090386/96633885-f7863080-12d6-11eb-8052-183e4b2454cc.png)

**Environment and Versions (please complete the following information):**
Using Python 3.8.5 with datadogpy v0.39.0 on MacOS Catalina 10.15.7

**Comment by zippolyte** [comment]
Hey @mencarellic, thanks for reporting this.
To send markdown, your event message must be enclosed in `%%% your_message %%%`. See https://github.com/DataDog/documentation/issues/364

Can you try with this ? I'll submit a PR to the documentation to add this note in.

**Comment by mencarellic** [comment]
Sorry, I'm a couple of days late here. That worked perfectly @zippolyte! Thank you!
