### ISSUE TITLE
Plugin failing to import modules

### ISSUE THREAD

**Issue by willfell** [DataDog/datadogpy#619]
Went through the documentation and have attempted multiple things but the callback plugin is unable to import one of the required modules. Below is the error found in the callback plugin directory under __pycache__/datadog_callback.cpython-36.pyc
`^@).Ú^NCallbackModulec^A^@^@^@^@^@^@^@^B^@^@^@^C^@^@^@C^@^@^@st^@^@^@t^@s^Td^A|^@_^At^Bd^B<83>^A^A^@n^^d^C|^@_^Ax^Vd^FD^@]^N}^A|^@j^C|^A<83>^A^A^@q W^@d^@|^@_^Dt^Ej^E<83>^@|^@_^Fd^@|^@_^Gt^@rdt^Hrdt    r\t
|^@_^Gn^Ht^Hj^K|^@_^Gd^@|^@_^Ld^@|^@_^Md^@S^@)^GNTzXDatadog callback disabled: missing "datadog", "yaml", and/or "packaging" python package.Fú^Yrequests.packages.urllib3ú^Kdatadog.api)^Br     ^@^@^@r
^@^@^@)^NÚ^KHAS_MODULESÚ^HdisabledÚ^EprintÚ^Q_set_logger_levelÚ^N_playbook_nameÚ^DtimeÚ^K_start_timeÚ^H_optionsr^F^@^@^@Ú^PANSIBLE_ABOVE_28r^G^@^@^@Ú^GoptionsÚ^HplaybookÚ^Dplay)^BÚ^DselfÚ^Hlog_name©^@r^Y^@^@^@ú7/usr/share/ansible/plugins/callback/datadog_callback.pyÚ^H__init__^]^@^@^@s^^^@^@^@^@^A^D^A^F^A
^B^F^B
^A^N^B^F^A
`

I have ran the following commands with no luck (I tried pip3 and also used pip2 to install after a test)
`pip3 install pyyaml
pip3 install datadog
pip3 install packaging`

Unable to find anything on google for this, would anyone happen to know root cause?

**Comment by therve** [comment]
Hi,

Can you move the issue to https://github.com/DataDog/ansible-datadog-callback? It looks unrelated to datadogpy. Thanks.
