### ISSUE TITLE
Empty values have different collection types

### ISSUE THREAD

**Issue by PeterJCLaw** [DataDog/datadogpy#620]
**Describe the bug**

`ServiceLevelObjective.get_all()` returns an empty list when there are no values, but otherwise a `dict`.
Observed when comparing `PRODUCTION=true` with a development setup, though it seems more likely this is an empty/non-empty issue than an environment issue.

**Expected behavior**

The return type of any method should be consistent.

**Environment and Versions (please complete the following information):**

Python 3.8.5
datadog 0.39.0    

**Additional context**

Not sure if this is an API client issue or a flaw in the underlying API.

**Comment by therve** [comment]
Hi,

Sorry for not responding earlier. I couldn't reproduce the issue, here's what I get when there is no SLOs: `{'data': [], 'error': None}` and with an SLO: `{'data': [{'description': ....'}], 'error': None}`. I don't think we have any type management in datadogpy anyway, so it may be a server issue? Let me know if you have a reproducer. Thanks.

**Comment by PeterJCLaw** [comment]
No worries. I've dug into this further and it turns out that the tool I was debugging has a local client it uses for development in place of connecting to DataDog and _that_ was returning `[]` :facepalm:. Sorry for the noise.
