### ISSUE TITLE
How to send datadog event stream data into datadog logs?

### ISSUE THREAD

**Issue by nags28** [DataDog/datadogpy#633]
Actually, we have two datadog accounts: Let me consider it has account A and account B. when I push the message to data dog event using API I am able to see the events in events stream and I am able to see the same thing in logs also in the account A. But when I do the same thing in account B I am able to see the data in event stream but not in logs. can I know what might be the reason ??? Am I missing something to enable ?? if so can someone help me with this?

BELOW CODE IS USED TO PUSH THE EVENT TO DATA EVENTS STREAM.

`from datadog import initialize, API

options = {
    'api_key': '<DATADOG_API_KEY>',
    'app_key': '<DATADOG_APPLICATION_KEY>'
}

initialize(**options)

title = "Something big happened!"
text = 'And let me tell you all about it here!'
tags = ['version:1', 'application:web']

api.Event.create(title=title, text=text, tags=tags)
`

**Comment by zippolyte** [comment]
Hey @nags28 

This looks like it isn't related to this library directly, but to the Datadog backend. Can you open a ticket with support (https://docs.datadoghq.com/help/) so they can look into this ? 

Thanks
