### ISSUE TITLE
api_instance.list_monitors() Api cannot read api from kubernetes secret

### ISSUE THREAD

**Issue by sandymaj** [DataDog/datadogpy#639]
Description:
I was trying to list the monitors which dont have a specific tag . The api_instance.list_monitors() api is able to list the monitors if I hardcode the api and auth key in python script, but making the script as Docker image and try to run as a cronjob in kubernetes, it fails with the error when I try to read the secret from kubernetes .

My Script:

`
import os
from dateutil.parser import parse as dateutil_parser
from datadog_api_client.v1 import ApiClient, ApiException, Configuration
from datadog_api_client.v1.api import monitors_api
from datadog_api_client.v1.models import *
from pprint import pprint
from datadog import initialize, api

def list_dd_monitors_not_in_tf(apiKeyAuth,appKeyAuth):
    # See configuration.py for a list of all supported configuration parameters.
    configuration = Configuration()
    # Configure API key authorization: apiKeyAuth
    configuration.api_key['apiKeyAuth'] = apiKeyAuth
    # Configure API key authorization: appKeyAuth
    configuration.api_key['appKeyAuth'] = appKeyAuth
    # Enter a context with an instance of the API client
    with ApiClient(configuration) as api_client:
        # Create an instance of the API class
        api_instance = monitors_api.MonitorsApi(api_client)

        try:
            total_monitors = 
            count_monitors = len(total_monitors)
            print(count_monitors)
            print(total_monitors[1]['tags'])
            
            count = 0
            for item in range(1,count_monitors):
                monitor_tags = total_monitors[item]['tags']
                if "terraform" not in str(monitor_tags):
                    count = count+1
            print(str(count) + " " + "monitors are created without Terraform ")
            api.Metric.send([{
                'metric': 'dd.monitors.not.in.terraform',
                'points': count,
                'tags': ["service:datadog","team:sre"]
            }])

        except ApiException as e:
            print("Exception when calling MonitorsApi->list_monitors: %s\n" % e)
            

if __name__ == "__main__":

    dd_api_key = os.getenv('DD_API_KEY')
    dd_auth_key = os.getenv('DD_AUTH_KEY')
    list_dd_monitors_not_in_tf(dd_api_key,dd_auth_key)
`

Log Trace:
kubectl logs -f dd-monitors-not-tf-cron-1614870720-2kq2k
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/datadog/api/api_client.py", line 180, in submit
    response_obj = json.loads(content.decode('utf-8'))
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 4 column 1 (char 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dd_monitors_not_in_tf.py", line 16, in <module>
    total_monitors = api.Monitor.get_all()
  File "/usr/local/lib/python3.8/site-packages/datadog/api/monitors.py", line 60, in get_all
    return super(Monitor, cls).get_all(**params)
  File "/usr/local/lib/python3.8/site-packages/datadog/api/resources.py", line 232, in get_all
    return APIClient.submit('GET', cls._resource_name, api_version, **params)
  File "/usr/local/lib/python3.8/site-packages/datadog/api/api_client.py", line 184, in submit
    raise ValueError('Invalid JSON response: {0}'.format(content))å
ValueError: Invalid JSON response: b'\n\n\n<!DOCTYPE html>\n<!--\n______  _______ _______ _______ ______   _____   ______\n|     \\ |_____|    |    |_____| |     \\ |     | |  ____\n|_____/ |     |    |    |     | |_____/ |_____| |_____|\n\n\n8fv2XLri3BZpeaw01YtZPJvZPQCXx/As42P0KAGfu7zLPcfitCu9euDm/7qkoY02TKT+Rr8yw+2yz+N0Da+EJaREB/Nj/SNze56w08EyNmPKQmJzv201fqFP8TyD2k34QeA3UaTx3bPmf0qKGVE06lsULGOqa7EdsVu95jfn3UiGBGpnLecZwFo9fxvpEu...

![image](https://user-images.githubusercontent.com/80055976/109991011-38bd3100-7d0a-11eb-9301-d8b76fd570cd.png)

**Comment by zippolyte** [comment]
Hey ! This looks like an issue for https://github.com/DataDog/datadog-api-client-python, can you reopen it there ?
Thanks
