### ISSUE TITLE
api.Tag.create Fails to Create Tags

### ISSUE THREAD

**Issue by stephendepatie** [DataDog/datadogpy#643]
**Describe the bug**
Receiving 502 when attempting to create tags. 

`api.Tag.create(host='0.0.0.0', body={'tags': ['sampletag:sample']}`

Returns:

```Datadog returned a bad HTTP response code: 502 - Bad Gateway. Please try again later. If the problem persists, please contact support@datadoghq.com```

The issue is the request is including a body key for the body: 

```{'body': {'tags': ['sampletag:sample']}}```

I've gotten around this by requesting the value of body in `api_client.py:160`

```       # Process the body, if necessary
            if isinstance(body, dict):
                body = body['body']  # <- Added this line
                body = json.dumps(body, sort_keys=cls._sort_keys)
                headers["Content-Type"] = "application/json"
```

There's probably a more eloquent solution but this works for now. 

Label the issue properly.
- Add `severity/` label.
- Add `documentation` label if this issue is related to documentation changes.

**To Reproduce**
Attempt to create a tag on any host in datadog.

**Expected behavior**
Successfully creates tag and returns JSON response

**Screenshots**

**Environment and Versions (please complete the following information):**
A clear and precise description of your setup:
- datadogpy version:  0.40.1
- Python 3.8.5

**Additional context**

**Comment by therve** [comment]
This is a bit confusing, but the right way to use that API is `api.Tag.create(host='0.0.0.0', tags=['sampletag:sample'])`. Let me know if that works for you.

**Comment by stephendepatie** [comment]
Thanks for the response, Thomas. That did indeed work!

Cheers
