### ISSUE TITLE
python2 datadog package is broken

### ISSUE THREAD

**Issue by kvitali** [DataDog/datadogpy#647]
**Describe the bug**
pip2 installation of datadog package fails

**To Reproduce**
1. pip2 install datadog

**Expected behavior**
Successful installation with decorator 4.4.2 package that supports python2

**Environment and Versions (please complete the following information):**
Ubuntu 18.04

**Additional context**
Output:
Collecting datadog
Downloading https://files.pythonhosted.org/packages/10/a0/2496cfa1d01676fa00bd717770ff2945ba3a809a494e196318621b90b432/datadog-0.40.1-py2.py3-none-any.whl (107kB)
100% |████████████████████████████████| 112kB 800kB/s
Requirement already satisfied: configparser<5; python_version < "3.0" in /usr/local/lib/python2.7/dist-packages (from datadog) (3.5.0)
Requirement already satisfied: requests>=2.6.0 in /usr/local/lib/python2.7/dist-packages (from datadog) (2.21.0)
Collecting decorator>=3.3.2 (from datadog)
Downloading https://files.pythonhosted.org/packages/71/bd/042e63027bea950da4e6f5545eb59b973868da854ab30a18128d3b884104/decorator-5.0.2.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "", line 1, in
File "/tmp/pip-install-tQUq1p/decorator/setup.py", line 4, in
exec(open('src/decorator.py').read(), dic) # extract the version
File "", line 162
print('Error in generated code:', file=sys.stderr)
^
SyntaxError: invalid syntax

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-tQUq1p/decorator/

**Comment by therve** [comment]
It seems to work with the latest decorator release. We have a workaround in our code which should be in the next release otherwise. Let me know if that still doesn't work.
