### ISSUE TITLE
"dog monitor unmute" dose not work

### ISSUE THREAD

**Issue by morihaya** [DataDog/datadogpy#648]
**Describe the bug**

We are using version 0.40.1 of Dogshell.
I was able to successfully mute it with the `dog monitor mute` command.
However, the `dog monitor unmute` command resulted in an error.

**To Reproduce**

1. `dog monitor mute xxxx`
2. `dog monitor unmute xxxx`
3. See error

```
bash-3.2$ dog monitor unmute 10176108
ERROR: log alert "my-service-dev-api Error" is already unmuted on

bash-3.2$ echo $?
1
bash-3.2$
```

**Expected behavior**

I want the `dog monitor unmute` command to succeed and the corresponding monitor to be muted.

**Environment and Versions (please complete the following information):**

```
bash-3.2$ dog -v
dog 0.40.1
bash-3.2$
bash-3.2$ python -V
Python 3.7.6
bash-3.2$
```

**Comment by therve** [comment]
Hi! Sorry not coming back to you earlier: you need to pass the scopes to unmute on, eg `dog monitor unmute 10176108 --all_scopes`. Let us know if it doesn't work, thanks.

**Comment by morihaya** [comment]
Thenk you @therve . It works 👍
