### ISSUE TITLE
api config is singleton like

### ISSUE THREAD

**Issue by pnegahdar** [DataDog/datadogpy#72]
https://github.com/DataDog/datadogpy/blob/master/datadog/api/__init__.py#L4

Why are these module level variables? Make it difficult to use and manage multiple API clients.

**Comment by yannmh** [comment]
Sorry to hear you had troubles using `datadogpy` @pnegahdar .

`datadog.api` Python package is entirely static, it does not play well with multiple API clients :confused: : information is shared among the different subpackages, by defining variables at the module level. 

Could you please tell me more about what you are trying to achieve ? Are you using `datadog.api` among the same Python project with multiple accounts ? Is it a fixed or dynamic number of accounts ?

A very dirty workaround for a small and fixed number of accounts, is to force the module to reimport, i.e.
```python
import datadog.api as api1
import sys
del sys.modules["datadog.api"]
import datadog.api as api2

api1._api_key = ...
api2._api_key = ...

api1.Metric.send(...)
api2.Metric.send()
```

Please let me know your use case, I'll be happy to work on a much proper solution. Thanks !

**Comment by yannmh** [comment]
@pnegahdar I haven't heard back from you.

I am closing this issue, but please feel free to re-open if you have additional questions or concerns. Thank you.

**Comment by BCjmiller** [comment]
@yannmh Is there any plan to change this implementation? What I'm trying to do is to track performance in parts of a service with `datadog.ThreadStats` that will eventually be posted to account `A`, in addition to getting event data on other services from a couple of other accounts. Having module-level variables makes this rather frustrating to implement.

**Comment by yannmh** [comment]
@BCjmiller This isn't something we

**Comment by yannmh** [comment]
@BCjmiller, 

This isn't something we originally planned to do. The library design was thought to be easy to play well with a single Datadog account. The majority of the code being __static__, fixing this would require a lot of code change and potentially to revisit the whole interface.

However as this is getting more and more interest, we realize that it's probably time to change that. We'll spend some time next week to assess how we can achieve this goal with a minimal impact on the interface, and will follow up on this issue.

**Comment by Daenyth** [comment]
@yannmh What was the assessment?

**Comment by Julian** [comment]
(+1 FWIW, there are lots of issues with this implementation for us as well which has always kept us using the older library.)

**Comment by iksaif** [comment]
+1, In particular because I use the datadog API with multiple accounts and want to try to do things in parallel. In some cases I re-implemented methods using `requests` directly.

I think there's a path to make it work:
* Change https://github.com/DataDog/datadogpy/blob/master/datadog/api/resources.py to have an optional `client` param
* Add a constructor to https://github.com/DataDog/datadogpy/blob/master/datadog/api/api_client.py that can take all the things that are in `__init__`

That should work for most things. This is basically what a swagger generated client would look like (for example: https://github.com/opsgenie/opsgenie-python-sdk/tree/master/opsgenie_sdk)

**Comment by zippolyte** [comment]
This won't be doable without a significant rework of the library, while keeping backward compatibility. 
However we are currently working on a new and fresh python library for interacting with Datadog's API that wouldn't have that issue. I can't share an exact ETA at the moment.
