### ISSUE TITLE
io.micrometer.datadog.DatadogMeterRegistry: failed to send metrics to datadog: {"status":"error","code":403,"errors":["Forbidden"],"statuspage":"http://status.datadoghq.com","twitter":"http://twitter.com/datadogops","email":"support@datadoghq.com"}

### ISSUE THREAD

**Issue by SakuraLxm** [DataDog/datadogpy#723]
I am setting up a signal server. The server I use does not have a domain name. Is it because there is no domain name to request?

 help

**Comment by therve** [comment]
Hello,

This doesn't seem to be related to datadogpy, can you open a support ticket? Thank you.

**Comment by SakuraLxm** [comment]
> sorry,i dont know what you mean.. Is my problem not related to this？Aren't datadog and datadogpy the same thing?

**Comment by SakuraLxm** [comment]
> Hello,
> 
> This doesn't seem to be related to datadogpy, can you open a support ticket? Thank you.

**Comment by SakuraLxm** [comment]
a
