### ISSUE TITLE
statsd.event should raise something more specific than Exception

### ISSUE THREAD

**Issue by tylertrussell** [DataDog/datadogpy#725]
**Is your feature request related to a problem? Please describe.**
The `statsd.event` function will `raise Exception` in the event the payload is invalid (i.e. too big).  This prevents users of the library from catching a specific exception, and could lead to other types of errors (e.g. `TypeError`) being "swallowed" when they should be allowed to propagate.

**Describe the solution you'd like**
Instead of `Exception`, the library should raise a `ValueError` (or some other more-specific `Exception` subclass).

**Describe alternatives you've considered**
Users of the library could catch an `Exception` and then try to compare the error message, which is not great.

Updating to remove stale tag; this is still reproducible.

**Comment by tylertrussell** [comment]
I confirm that I can still reproduce this issue in the latest version of the project.

There is an open PR #730 that addresses this issue, it would be excellent to have that reviewed by the relevant parties at some point soon.

**Comment by sgnn7** [comment]
@tylertrussell The [linked PR](https://github.com/DataDog/datadogpy/pull/730) has been merged so it should be out with the next release of this library (probably `0.45.x`). I'll mark this issue as closed but feel free to reopen if needed.
