### ISSUE TITLE
Issue when parsing metrics containing "NaN" in the value field

### ISSUE THREAD

**Issue by mcpate** [DataDog/datadogpy#73]
I have a Dropwizard project that ships a bunch of metrics to dogStatsD.  When the app is initialized there are a few metrics that report "NaN" in the value field (this will happen until requests start coming in).  I notice that during this time dogStatsD is throwing exceptions that then get logged (in our case, they get logged into SumoLogic which we are paying for by "space used").

It would be nice if dogStatsD handled this type of field since it is a part of the Java language specification.  It seems that "NaN" should result in a value of 0 (in the case of the Dropwizard metrics, it is the case of "0.0d / 0.0") especially when being used for metrics.

**Comment by yannmh** [comment]
Thanks for reporting @mcpate. Would you be able to provide the exception stack please ?

**Comment by mcpate** [comment]
```
dd.dogstatsd[15]: ERROR (dogstatsd.py:308): Error receiving datagram
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/dogstatsd.py", line 296, in start
    aggregator_submit(message)
  File "/opt/datadog-agent/agent/aggregator.py", line 599, in submit_packets
    parsed_packets = self.parse_metric_packet(packet)
  File "/opt/datadog-agent/agent/aggregator.py", line 474, in parse_metric_packet
    raise Exception('Metric value must be a number: %s, %s' % (name, raw_value))
Exception: Metric value must be a number: cns.io.dropwizard.jetty.MutableServletContextHandler.percent-5xx-5m, ?
```

**Comment by yannmh** [comment]
Thanks @mcpate !

It looks like the issue you are describing is related with [dd-agent](https://github.com/DataDog/dd-agent), not `datadog` Python library. 
Would you mind re-opening the ticket on the right repository ? That way, It would be easier for us to reach you out and keep you post on the progress made :smiley:

**Comment by mcpate** [comment]
Will do.  Thanks!
