### ISSUE TITLE
Error handling: APIError is never raised

### ISSUE THREAD

**Issue by MartinDatadog** [DataDog/datadogpy#74]
This library never returns the status code of the http request.
Instead, when the status code is 400, 403 or 404, it is supposed to raise an APIError exception with the content of the errors field received from the dispatcher.(https://github.com/DataDog/datadogpy/blob/master/datadog/api/base.py#L152).
For all other 3, 4, 5** status codes, an HTTPError is raised.

So catching errors and interacting with the API should be a matter of catching APIError and HTTPError exceptions.

BUT, the `_swallow` attribute prevents APIError to be raised (https://github.com/DataDog/datadogpy/blob/master/datadog/api/base.py#L171-L172). It's set to True in api/__init__.py and is not modifiable at the moment.

A temporary workaround is to use `from datadog import api api._swallow = False`.

We could evaluate the impact of a potential transition to swallow being True by default and also being set up when initializing the api.

**Comment by yannmh** [comment]
Thanks for all the details @MartinDatadog. 

As detailed in your post, `_swallow` parameter is  by default set to `True`. The reason behing this was to mimic the behavior of its ancestor, `dogapi`. 

I think it would make more sense to have it set to `False` by default, and potentially switch it back to `True` using the `initialize` method.

I added the ticket to the 1.0.0 milestone: this change would potentially introduce backward incompatibilities. In the mean time, the work around you wrote should just work fine !

**Comment by yannmh** [comment]
Let's make it settable from `initialize` method.

```python
from datadog import api, initialize

options = {
    'api_key':'api_key',
    'app_key':'app_key',
    'swallow': False
}

initialize(**options)
```

We could switch the default value from `True` to `False` in the 1.0.0 release.
