### ISSUE TITLE
Fix SLO search

### ISSUE THREAD

**Issue by Throckmortra** [DataDog/datadogpy#741]
Please expose SLO search api https://docs.datadoghq.com/api/latest/service-level-objectives/#search-for-slos

OR

Please fix the get_all api such that the library allows for using tag filters https://docs.datadoghq.com/api/latest/service-level-objectives/#get-all-slos

Currently the way the get_all query works is quite opaque and ignores all tag filtering

**Comment by Throckmortra** [comment]
https://github.com/DataDog/datadogpy/blob/master/datadog/api/service_level_objectives.py#L71

**Comment by therve** [comment]
Fixed in #744
