### ISSUE TITLE
Error while pushing metrics to datadog (AttributeError: 'str' object has no attribute 'get')

### ISSUE THREAD

**Issue by mrigank002** [DataDog/datadogpy#743]
This is what my metrics is:
metrics={
                    "series": [
                      {
                        "type": "rate",
                        "interval":1,
                        "host": "GitLab",
                        "metric": "thl.certificate.days.test",
                        "tags": [
                          "source:vault",
                          "sre-environment:dev",
                          "sre-appstackcode:odccsm",
                          "namespace:namespace",
                          "name:name",
                          "region:region",
                          "trigram:trigram",
                          "purpose:purpose"
                        ],
                        "points": [
                          [
                            time.time(),
                            "5"
                          ]
                        ]
                      }
                    ]
                }

api.Metric.send(metrics=metrics)

error:

Traceback (most recent call last):
  File "/home/gitlab-runner/builds/wkpzw2iM/0/mcs/odc/certificate-operations/datadog_test.py", line 47, in <module>
    api.Metric.send(metrics=metrics)
  File "/home/gitlab-runner/.local/lib/python3.10/site-packages/datadog/api/metrics.py", line 109, in send
    return super(Metric, cls).send(
  File "/home/gitlab-runner/.local/lib/python3.10/site-packages/datadog/api/resources.py", line [80](https://gitlab.sre.ops.gcloud.thalescloud.io/mcs/odc/certificate-operations/-/jobs/1392736#L80), in send
    return APIClient.submit(
  File "/home/gitlab-runner/.local/lib/python3.10/site-packages/datadog/api/api_client.py", line 145, in submit
    if obj_params.get("host", "") == "":
AttributeError: 'str' object has no attribute 'get'

**Comment by mrigank002** [comment]
This obj_params is a dictionary and it should run .get method. But I don't know why it is throwing exception.

**Comment by mrigank002** [comment]
when I am running this code in my machine for tis dict it is working fine:

for obj_params in metrics["series"]:
   print(obj_params.get("host", ""))

**Comment by therve** [comment]
Hi,

Sorry for not responding earlier. The issue is that you have a `series` key which should not be here. Here's a working example:

```python
metrics = [
    {
        "type": "rate",
        "interval": 1,
        "host": "GitLab",
        "metric": "thl.certificate.days.test",                                                                                                                 
        "tags": [
            "source:vault",
            "sre-environment:dev",
            "sre-appstackcode:odccsm",                                                                                                                         
            "namespace:namespace",
            "name:name",
            "region:region",
            "trigram:trigram",                                                                                                                                 
            "purpose:purpose",
        ], 
        "points": [[time.time(), 5]],
    }
]

api.Metric.send(metrics=metrics)
```
