### ISSUE TITLE
Dogshell broken on Python 3.11

### ISSUE THREAD

**Issue by allen-stubberud** [DataDog/datadogpy#746]
**Describe the bug**
`argparse` logic is broken on Python 3.11. Setting up the argument parser throws an exception before any arguments can be parsed. This [issue](https://github.com/Azure/azure-cli/issues/23015#issuecomment-1268587028) in an unrelated project might be relevant.

**To Reproduce**
1. Invoke dogshell on the command line: `# dog`

**Expected behavior**
The command line parser does not crash.

**Screenshots**
```
# dog
Traceback (most recent call last):
  File "/usr/local/bin/dog", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/datadog/dogshell/__init__.py", line 96, in main
    DashboardListClient.setup_parser(subparsers)
  File "/usr/local/lib/python3.11/site-packages/datadog/dogshell/dashboard_list.py", line 128, in setup_parser
    delete_dashboards_v2_parser = verb_parsers.add_parser(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/argparse.py", line 1185, in add_parser
    raise ArgumentError(self, _('conflicting subparser: %s') % name)
argparse.ArgumentError: argument verb: conflicting subparser: delete_dashboards
```

**Environment and Versions (please complete the following information):**
Python 3.11 (Alpine Linux)
Datadogpy 777377105f2aaaaeb6ddd98abb4c90815c95589c

**Comment by latch-danielkneip** [comment]
This is still an issue.
