### ISSUE TITLE
syntax error during initialization

### ISSUE THREAD

**Issue by heytrav** [DataDog/datadogpy#82]
I'm trying to run some code in python3.4 with datadog and keep seeing the following error:
```
from datadog import initialize
File "/opt/datadog-agent/agent/checks/datadog.py", line 168
self._error_count = 0L
                     ^
```

Is this a python3 compatibility issue?

**Comment by yannmh** [comment]
Hi @heytrav ,
It seems like you have a name conflict here: instead of importing the proper _datadog_ Python package, Python is importing this file instead `/opt/datadog-agent/agent/checks/datadog.py` from _datadog-agent_. 

Could you give us more context about what you are trying to accomplish please ? Is your code meant to be part of _datadog-agent_ project ? Thanks

**Comment by heytrav** [comment]
Thanks for the tip.

I'm trying to use this inside of a docker container. I've installed the datadog agent using the ubuntu steps and in the container I've installed datadog using `pip install datadog`. For some reason calling `from datadog import initialize` in my code seems to be picking up the library  under `/opt/datadog-agent/agent` instead of the one I installed using `pip`. I'm trying to work out why at the moment.

**Comment by yannmh** [comment]
Sorry to hear you have trouble using _Datadog agent_ and _datadog_.

From http://www.tutorialspoint.com/python/python_modules.htm, about Python module search path:
> The module search path is stored in the system module sys as the sys.path variable. The sys.path variable contains the current directory, PYTHONPATH, and the installation-dependent default.

Is your Python project using _datadog_ located in `/opt/datadog-agent/agent/checks/` directory ? If not could you check your `sys.path` variable (`import sys; print sys.path`)? It should help understanding why it's picking up the package in the wrong place.

**Comment by heytrav** [comment]
In the meantime I've got this sorted. I was using supervisor to start the agent using the shipped supervisord.conf. Since I was building this into a docker container I didn't know how to get it to start separately but now I'm running it in a bash script.
