### ISSUE TITLE
Monitor query DSL

### ISSUE THREAD

**Issue by mausch** [DataDog/datadogpy#98]
It would be really nice to have a DSL to define monitor queries as opposed to having to build and send strings.

**Comment by StephenWeber** [comment]
This would also help with consuming existing monitor queries, such as ensuring that the scope does not contain problematic tags. Writing regex / string-parsing to cover all cases is getting tedious.

**Comment by yannmh** [comment]
Seems like a nice feature, thanks for the further explanations ! 

Adding it to triage so we can consider it for an upcoming release.

**Comment by sprutner** [comment]
I also concur that this would be nice.

Would it be possible to have the validation regexes used by the DD API shared? It seems like a lot of people are building their own regexes around this when it might be easier if we could work off of the official ones.

**Comment by zippolyte** [comment]
The way we recommend solving this, is by calling the dedicated [monitor validate](https://docs.datadoghq.com/api/?lang=bash#validate-a-monitor) endpoint, which is implemented in this library as well.
